-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 26, 2024 lúc 07:57 PM
-- Phiên bản máy phục vụ: 10.4.32-MariaDB
-- Phiên bản PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `duan1_database`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tbl_sanpham`
--

CREATE TABLE `tbl_sanpham` (
  `masanpham` int(11) NOT NULL,
  `tensp` varchar(60) NOT NULL,
  `don_gia` double(11,2) NOT NULL DEFAULT 0.00,
  `ton_kho` int(3) NOT NULL DEFAULT 100,
  `images` text NOT NULL,
  `giam_gia` double(10,2) NOT NULL DEFAULT 0.00,
  `dac_biet` tinyint(1) NOT NULL DEFAULT 0,
  `so_luot_xem` int(11) NOT NULL DEFAULT 0,
  `ngay_nhap` datetime NOT NULL,
  `date_modified` datetime NOT NULL DEFAULT current_timestamp(),
  `mo_ta` text NOT NULL,
  `ma_danhmuc` int(11) NOT NULL,
  `id_dmphu` int(3) NOT NULL,
  `information` text NOT NULL,
  `promote` tinyint(1) NOT NULL DEFAULT 0,
  `danhgia` float(1,1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `tbl_sanpham`
--

INSERT INTO `tbl_sanpham` (`masanpham`, `tensp`, `don_gia`, `ton_kho`, `images`, `giam_gia`, `dac_biet`, `so_luot_xem`, `ngay_nhap`, `date_modified`, `mo_ta`, `ma_danhmuc`, `id_dmphu`, `information`, `promote`, `danhgia`) VALUES
(1, 'Cây hoa tường vi', 350000.00, 100, 'oppo - reno 5g 8t den.png,oppo-reno8t-den1-thumb-600x600.jpg,oppo-reno-5g-dep.jpg,638091158554197072_oppo-reno8-t-5g-dd.jpg,Oppo Reno 5G.png,oppo-reno-8t.jpg,thumb-oppo-reno8t-vang1-thumb-600x600.jpg', 5.00, 1, 22, '2024-11-26 09:20:03', '0000-00-00 00:00:00', '2024-10-22 20:34:57', 0, 1, '<p>Cây hoa tường vi có kích thước chưa lên chậu khoảng 80cm - 100cm. Tuy nhiên cây có rất nhiều loại kích thước cũng như màu hoa. Nếu quý khách hàng muốn mua loại kích thước nào có thể nhắn tin trực tiếp để được tư vấn, cũng như gửi hình cây thực tế</p>\r\n', 3, 0.0),
(2, 'Cây Hoa Giấy', 250000.00, 59, 'cayhoagiay1.jpg,cayhoagiay2.jpg,cayhoagiay3.jpg,cayhoagiay4.jpg,cayhoagiay5.jpg', 0.00, 0, 19, '2023-03-11 08:13:17', '2023-03-14 15:25:01', 'Cây có chiều cao khoảng 60-80cm khi chưa lên chậu. Ngoài ra còn rất nhiều loại khác nhau kể cả về kích thước , lẫn màu hoa. Nên quý khách có thể liên hệ để chọn loại ưa thích và phù hợp.', 1, 3, '<p>Đặc điểm của cây hoa giấy</p> Cây hoa giấy thuộc họ Nyctaginaceae và có tên khoa học là Bougainvillea. Đây là loại cây leo thân gỗ, có thể leo cao đến 10 mét hoặc hơn nếu được chăm sóc đúng cách. Cây hoa giấy phát triển mạnh mẽ và có nhiều giống loài khác nhau, mỗi giống mang một vẻ đẹp và đặc trưng riêng biệt. 
<p>Thân cây: Hoa giấy có thân gỗ mềm mại, dễ uốn nắn, rất thích hợp để tạo dáng bonsai hoặc leo giàn. Thân cây có màu nâu xám, có gai và thường phát triển theo chiều hướng bò ngang hoặc leo lên cao.</p> 
<p>Lá cây: Lá cây hoa giấy có hình bầu dục, nhọn ở đầu, màu xanh đậm, bóng láng và có thể có lớp lông mịn. Lá thường mọc đối, tạo thành những mảng lá xanh mướt làm nền cho những chùm hoa rực rỡ. Hoa: Hoa giấy thực chất là những lá bắc có màu sắc rực rỡ, bao quanh các bông hoa nhỏ màu trắng hoặc vàng nhạt bên trong. Các lá bắc này thường có nhiều màu sắc đa dạng như hồng, đỏ, cam, tím, vàng, trắng,… Đây chính là điểm nhấn chính tạo nên vẻ đẹp đặc trưng của cây hoa giấy. </p>
<p>Ý nghĩa phong thủy của cây hoa giấy Cây hoa giấy không chỉ là một loài cây cảnh đẹp mắt mà còn mang ý nghĩa phong thủy sâu sắc, được nhiều người tin rằng sẽ đem lại may mắn và tài lộc cho gia đình. </p>
<p>Dưới đây là những ý nghĩa phong thủy chính của cây hoa giấy: Xua đuổi tà khí, bảo vệ gia đình Trong phong thủy, cây hoa giấy được coi là một loại cây có khả năng xua đuổi tà khí, bảo vệ ngôi nhà khỏi những điều xui xẻo. Đặc biệt, việc trồng hoa giấy ở cổng nhà, giàn leo hoặc gần cửa ra vào sẽ tạo nên một lớp “lá chắn” bảo vệ, ngăn chặn những năng lượng xấu xâm nhập vào không gian sống. Mang lại may mắn và thịnh vượng Hoa giấy tượng trưng cho sự bền bỉ và kiên cường, giống như cách mà cây vẫn phát triển mạnh mẽ trong điều kiện khắc nghiệt. Việc trồng cây hoa giấy trong nhà không chỉ tạo cảnh quan đẹp mà còn thu hút vượng khí, mang lại may mắn và tài lộc cho gia chủ. Đặc biệt, những bông hoa giấy rực rỡ màu sắc được cho là sẽ giúp thu hút năng lượng tích cực, làm gia đình hạnh phúc và thịnh vượng hơn. Biểu tượng của tình yêu bền vững Hoa giấy cũng được xem là biểu tượng của tình yêu và sự gắn kết. Màu sắc rực rỡ của hoa giấy đại diện cho tình cảm nồng cháy, còn sự bền bỉ của cây biểu tượng cho sự chung thủy và bền vững trong tình yêu. Nhiều cặp đôi lựa chọn trồng hoa giấy như một cách để thể hiện tình cảm và ước muốn gắn bó dài lâu. Sự phát triển và thăng tiến trong công việc Theo quan niệm phong thủy, cây hoa giấy còn biểu tượng cho sự phát triển, thăng tiến trong công việc và sự nghiệp.</p> 
<p>Trồng cây hoa giấy trong văn phòng hoặc khu vực làm việc sẽ giúp thu hút cơ hội, may mắn và sự thăng tiến trong công việc. Tăng cường năng lượng dương, cân bằng âm dương Hoa giấy có màu sắc tươi sáng, thuộc hành Hỏa trong ngũ hành, do đó cây có tác dụng tăng cường năng lượng dương, giúp cân bằng âm dương trong không gian sống. Điều này rất quan trọng trong phong thủy, vì khi năng lượng dương được cân bằng, nó sẽ mang lại cảm giác hài hòa, thoải mái và tốt lành cho gia đình. Biểu tượng của sự tự do và thoải mái Hoa giấy với khả năng phát triển mạnh mẽ, không bị gò bó bởi môi trường sống, thường được ví như biểu tượng của sự tự do, thoải mái. Trồng hoa giấy trong nhà giúp gia chủ cảm thấy tự do, không bị ràng buộc bởi những lo lắng và căng thẳng trong cuộc sống.</p>', 0, 0.0),
(3, 'Cây Cau Nga Mi', 650000.00, 88, 'caycaongami1.jpg,caycaongami2.jpg,caycaongami3.jpg,caycaongami4.jpg,caycaongami5.jpg', 5.00, 0, 14, '2023-03-11 02:25:13', '2023-04-11 10:35:02', '<p>Cây có chiều cao lộ thân từ 50cm - 3m. Giá cây sẽ phụ thuộc vào độ cao. Giá được tính theo mét thoát thân. Cây phù hợp để nơi nhiều ánh sáng như ban công, sảnh, sân vườn.</p>\r\n<quillbot-extension-portal></quillbot-extension-portal>', 1, 3, '<p>Cây cau nga mi hay còn gọi chà là cảnh, với tên khoa học Phoenix roebelenii. Là một trong những loài cây cảnh được yêu thích hiện nay. Xuất xứ từ các khu rừng nhiệt đới ẩm ướt ở Đông Nam Á, cây đã chinh phục trái tim của những người yêu cây cảnh bởi vẻ đẹp thanh lịch, sang trọng và khả năng thanh lọc không khí tuyệt vời. Với chiều cao khiêm tốn và dáng vẻ uyển chuyển, cây trở thành điểm nhấn độc đáo cho mọi không gian sống. Đặc điểm sinh học cây cau nga mi
Cây có những được điểm khá giống với cau cảnh, tuy nhiên vẫn có một số các đặc điểm khác để phân biệt chúng ta có thể tìm hiểu ở dưới đây.
<p>Thân cây: Thân cây thường mọc đơn lẻ, có màu nâu và mang nhiều dấu vết của cuống lá đã rụng. Đường kính thân cây tương đối nhỏ so với các loại cau khác, tạo nên vẻ đẹp thanh thoát.<p/>
<p>Lá: Lá cây có hình dáng lông chim, dài và mảnh mai, màu xanh đậm. Phần đầu lá hơi cong, tạo nên vẻ đẹp mềm mại và uyển chuyển. Lá cau nga mi thường mọc tập trung ở đỉnh thân, tạo thành một tán lá tròn đều.<p/>
<p>Hoa của cây cau nga mi</p>
<p>Hoa và quả: Cây cau rất ít khi ra hoa và kết quả trong điều kiện trồng cảnh. Hoa của cây thường nhỏ, màu vàng nhạt và mọc thành chùm. Quả cau có hình bầu dục, màu vàng nâu khi chín.</p>
<p>Hệ rễ: Hệ rễ của cây là rễ chùm phát triển tương đối phát triển, giúp cây bám chắc vào đất và hấp thụ nước, chất dinh dưỡng.</p>
<p>Ý nghĩa phong thủy và công dụng cau nga mi</p>
Cây ít được chú ý đến về ý nghĩa phong thủy, thường được chọn vì hình dáng cây đẹp. Tuy nhiên về mặt phong thủy lẫn tác dụng lọc khí đều cũng rất tốt.
<p>Phong thủy: Trong phong thủy, cây tượng trưng cho sự may mắn, tài lộc và sức khỏe. Cây giúp cân bằng giữa âm và dương, tạo ra một không gian sống hài hòa và thư thái. Người ta tin rằng, cây cau Nga Mi có khả năng hút tài lộc vào nhà và xua đuổi tà khí.</p>
Thanh lọc không khí: Cây có khả năng hấp thụ các chất độc hại trong không khí như formaldehyde, benzene, giúp không gian sống trở nên trong lành hơn. Đặc biệt, cây rất thích hợp trồng quán cà phê, cảnh quan sân vườn, ban công một không gian thư giãn.
Trang trí: Với vẻ đẹp thanh lịch và sang trọng, cây được sử dụng rộng rãi để trang trí nội thất, văn phòng, nhà hàng, khách sạn… Cây có thể trồng riêng hoặc chung với các loại cây cảnh khác để tạo nên những tiểu cảnh đẹp mắt.', 1, 0.0),
(4, 'Cây Hạnh Phúc Gốc To', 11990000.00, 78, 'cayhanhphucto1.jpg,cayhanhphucto2.jpg,cayhanhphucto3.jpg,cayhanhphucto4.jpg,cayhanhphucto5.jpg,', 10.00, 0, 7, '2023-03-11 02:40:37', '2023-03-14 15:25:01', '<p>Cây có chiều cao cả chậu giao động từ 1m6 cho đến gần 3m. Tán lá không quá dày rất phù hợp để trong nhà, văn phòng và làm quà tặng khai trương, nhà mới, đối tác...', 1, 3, 'Cây hạnh phúc gốc to còn được gọi với tên khoa học là Radermachera sinica, là một loại cây cảnh phổ biến được ưa chuộng bởi vẻ đẹp sang trọng, ý nghĩa may mắn và khả năng thanh lọc không khí hiệu quả.</p>

<p>cây hạnh phúc gốc to để văn phòng</p>
<p>Đặc điểm của cây hạnh phúc gốc to:</p>
<p>Tên khoa học: Sterculia foetida L.</p>
<p>Họ: Sterculiaceae</p>
<p>Chiều cao: Cây trưởng thành có thể cao tới 10 mét</p>
<p>Kích thước: Cây hạnh phúc gốc to có chiều cao trung bình từ 1,5 mét đến 4 mét, tán cây rộng và sum xuê.</p>
<p>Thân cây: Gốc to, xù xì, có màu nâu xám, thường được chia làm 3 nhánh biểu tượng cho tài lộc.</p>
<p>Lá cây: Mọc đối xứng, to bản, dày dặn, có hình bầu dục nhọn hai đầu, mép nguyên, mặt trên bóng loáng, mặt dưới nhám. Lá cây có màu xanh đậm, xanh thẫm hoặc xanh lục tùy thuộc vào độ tuổi và điều kiện chăm sóc.</p>
<p>Hoa: Mọc thành chùm ở đầu cành, có màu trắng ngà, hương thơm dịu nhẹ. Hoa thường nở vào mùa hè và thu.</p>
<p>Quả: Hình hạt đậu, khi chín có màu nâu đen, bên trong chứa hạt màu nâu đỏ.</p>
<p>hoa cây hạnh phúc</p>
<p>Hoa của cây hạnh phúc có mùi thơm nhẹ</p>

<p>Ý nghĩa phong thủy:</p>
<p>Mang lại may mắn, tài lộc: Cây hạnh phúc được mệnh danh là “cây tiền tài”, “cây may mắn” bởi tên gọi của nó và hình dáng lá cây xòe rộng như bàn tay hứng tài lộc.
Tượng trưng cho sự sung túc, thịnh vượng: Cây hạnh phúc gốc to với kích thước to lớn, tán lá sum suê tượng trưng cho sự sung túc, thịnh vượng và trường thọ.</p>', 0, 0.0),
(5, 'Cây Xoài', 2590000.00, 94, 'cayxoai1.jpg,cayxoai2.jpg,cayxoai3.jpg,cayxoai4.jpg,cayxoai5.jpg', 12.00, 0, 6, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'Cây có nhiều quy cách và đường kính để phù hợp với công trình của bạn, đường kính phổ biến là từ 15cm đến 30cm đo cách gốc 1m. Cây có hàng đánh thẳng lẫn giâm ủ. Quý khách vui lòng liên hệ được giá chính xác.', 1, 1, 'Cây Xoài là một trong những loại cây được top đầu được lựa chọn làm cây công trình, bóng mát. Vì sao cây được lựa chọn? Xoài công trình với xoài ăn quả có gì khác nhau mời các bạn cùng tìm hiểu ở bài viết dưới đây.

<p>Đặc điểm của cây Xoài</p>
<p>Tên thường gọi: Cây xoài, cây xoài ta, xoài úc, xoài tượng, xoài thái, xoài cát…</p>
<p>Tên tiếng anh: Mango.</p>
<p>Tên khoa học: Mangifera indica L.</p>
<p>Họ thực vật: chi Xoài thuộc họ Ðào lộn hột (Anacardiaceae) là một loại cây ăn quả nhiệt đới.</p>
<p>Nguồn gốc xuất xứ: Cây giống có nguồn gốc đến từ các nước có khí hậu nhiệt đới ở Châu Á.</p>
<p>Phân bố: Năm 1997, trung tâm cây ăn quả Long Định tuyển chọn ở Việt Nam du nhập một giống xoài nguồn gốc từ Ấn Độ có tên gọi là Xoài Cát Hòa Lộc và được nhân giống tại tỉnh Tiền Giang.</p>
<p>Hiện nay, cây được trồng ở khắp Việt Nam và nhiều giống khác nhau.</p>
<p>Thân và cành: Cây thuộc loại cây gỗ lớn, sống lâu năm. Có chiều cao trung bình từ 10 – 30m. Tuy nhiên, tùy vào độ tuổi và giống cây khác nhau mà độ lớn của cành và tán lá sẽ có sự chênh lệch.</p>
<p>Thân của cây có màu nâu sậm hoặc trắng khi già.</p>
<p>Rễ: Cây có rễ cọc có thể ăn sâu xuống đất từ 5 – 8m, giúp cây có thể chịu hạn và đứng vững trãi. Rễ tập trung quanh gốc ở phạm vi 2m.</p>
<p>Lá: Hình dáng thon dài, nhỏ và mảnh mai, cây thuộc dạng lá đơn. Các cánh lá mọc so le, xen kẽ qua các cành cây, có chiều dài khoảng từ 15 – 30cm.</p>
<p>Một trong những ưu điểm của cây là rất ít rụng lá. Chính vì thế mà cây được chọn làm cây công trình.</p>
<p>Lá cây khi non sẽ có màu hồng cam sau đó là ngả sang đỏ sẫm, mặt lá bóng mượt và có màu xanh đậm khi trưởng thành. Tùy theo điều kiện môi trường sống mà một cây có thể cho ra 3 – 4 đợt chồi trong 1 năm.</p>
<p>Hoa: Mọc thành chùm kép ở ngọn cành, chùm dài khoảng 30cm, có 200 – 400 hoa trên một chùm, có màu vàng và nhỏ, gồm 5 đài nhỏ và một lớp lông trắng phía ngoài, cả 5 cánh hoa đều có tuyến mật, chỉ có 2 nhị trong số 5 nhị sẽ sinh sản được.</p>
<p>Các chùm hoa có màu vàng, mùi thơm nhẹ. Bình thường cây sẽ trổ hoa vào 2 vụ trong năm đó là: mùa đông và mùa hè.</p>
<p>Mỗi một chùm hoa xoài sẽ có 2 loại: lưỡng tính và hoa đực. Hoa lưỡng tính sẽ chiếm khoảng 1 – 36%. Cây thuộc loại giống thụ phấn chéo, phụ thuộc vào côn trùng đưa phấn là chủ yếu. Thời điểm thụ phấn tốt nhất là lúc mặt trời mọc, nhụy đực tung phấn vào khoảng từ 8 – 10 giờ sáng.</p>
<p>Quả: Có màu xanh mướt bên ngoài vỏ khi còn non, chuyển dần sang vàng đều khi chín, thịt quả vàng, thơm, bên trong nhân có xơ. Về độ ngọt thì tùy thuộc vào giống cây trồng về kích thước, hình dạng, màu sắc sẽ cho độ ngọt khác nhau. Hình dáng của quả là tròn hoặc hình bầu dục có chiều dài khoảng 5 – 25cm.</p>
<p>Hạt: Cứng và kích thước to, nhỏ tùy giống cây. Vỏ bên ngoài quả khi chín sẽ mềm như da, mịn và bóng loáng, có một hương đặc trưng, ngọt dịu. Đặc biệt, những quả trưởng thành cho ra hạt sẽ dễ nảy mầm và trồng tốt hơn.</p>
Sự khác nhau giữa cây xoài công trình và xoài ăn quả
<p>Xoài ăn quả thì có rất nhiều loại phổ biến nhất ở nước ta là các loại: Xoài cát Hòa Lộc, keo, cát chu, tượng, Úc, Thái, Tứ Quý, Ngọc Vân…</p>
<p>Xoài ăn quả: Thường được trồng chủ yếu để lấy quả nên cây được triết hoặc ghép mắt ở các thân cây mẹ để cho nhanh ra trái và độ cao thấp để dễ dàng vặt và thu hoạch.</p>
<p>Xoài công trình: Cây được trồng từ hạt, thường sẽ không quá quan trọng về chất lượng quả vì cây cao rất khó vặt quả. Đổi lại cây tạo ra nhiều bóng mát, không gây vướng ở khu vực tầm nhìn phía dưới.</p>
<p>Cây xoài công trình sẽ được chọn có thoát thân từ 1m8 trở lên. Cây không sâu mục, cành tán đều. Đường kính thân từ 10 – 60cm.</p>', 0, 0.0),
(6, 'Cây Trúc Nhật Vàng
 ', 5990000.00, 95, 'thumb-a96-navigation-pink-v1.png,a96 pink oppo qua dep.png,a96 pink dien thoai rat dep.png,a 96 pink dien thoai oppo.png,oppo 96 dien thoai.jpg,a96-pink-1920.png', 8.00, 0, 5, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'OPPO A96 là cái tên được nhắc đến khá nhiều trên các diễn đàn công nghệ hiện nay, nhờ sở hữu một ngoại hình hết sức bắt mắt cùng hàng loạt các thông số ấn tượng trong phân khúc giá như hiệu năng cao, camera chụp ảnh sắc nét.\r\nNổi bật với diện mạo đầy cuốn hút\r\nHiển thị hình ảnh một cách sinh động\r\nSử dụng lâu hơn nhờ trang bị viên pin lớn\r\nChiến game ổn định nhờ chip xử lý đến từ Qualcomm\r\n', 1, 1, 'Màn hình:\r\n\r\nIPS LCD6.59\"Full HD+\r\nHệ điều hành:\r\n\r\nAndroid 11\r\nCamera sau:\r\n\r\nChính 50 MP & Phụ 2 MP\r\nCamera trước:\r\n\r\n16 MP\r\nChip:\r\n\r\nSnapdragon 680\r\nRAM:\r\n\r\n8 GB\r\nDung lượng lưu trữ:\r\n\r\n128 GB\r\nSIM:\r\n\r\n2 Nano SIMHỗ trợ 4G\r\nPin, Sạc:\r\n\r\n5000 mAh33 W', 0, 0.0),
(7, 'Điện thoại OPPO A77s', 6290000.00, 98, 'thumb-combo_a77s-_en_2.jpg,oppo a77s dep qua dep.jpg,a77 oppo chuan star.jpg,oppo a77 xanh chuan.jpg,oppo a 77 xanh blue.jpg,combo_a77s-_xanh_1.jpg,oppo-a77s-xanh.jpg', 0.00, 0, 4, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'OPPO vừa cho ra mắt mẫu điện thoại tầm trung mới với tên gọi OPPO A77s, máy sở hữu màn hình lớn, thiết kế đẹp mắt, hiệu năng ổn định cùng khả năng mở rộng RAM lên đến 8 GB vô cùng nổi bật trong phân khúc.\r\nLinh hoạt hơn với khả năng xử lý đa tác vụ\r\nVẻ ngoài cao cấp\r\nGiải trí đã mắt với màn hình lớn\r\nTận hưởng vô tư, lo chi gián đoạn', 1, 1, 'Màn hình:\r\n\r\nIPS LCD6.56\"HD+\r\nHệ điều hành:\r\n\r\nAndroid 12\r\nCamera sau:\r\n\r\nChính 50 MP & Phụ 2 MP\r\nCamera trước:\r\n\r\n8 MP\r\nChip:\r\n\r\nSnapdragon 680\r\nRAM:\r\n\r\n8 GB\r\nDung lượng lưu trữ:\r\n\r\n128 GB\r\nSIM:\r\n\r\n2 Nano SIMHỗ trợ 4G\r\nPin, Sạc:\r\n\r\n5000 mAh33 W', 0, 0.0),
(8, 'Điện thoại OPPO A76', 5390000.00, 98, 'thumb-combo_a76_-_black.jpg,oppo-a76-3.jpg,a76 combo blue chuan.jpg,combo_a76_blue_dep.jpg,combo_a76_-_blue.jpg,', 10.00, 0, 5, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'OPPO A76 4G ra mắt với thiết kế trẻ trung, hiệu năng ổn định, màn hình 90 Hz mượt mà cùng viên pin trâu cho thời gian sử dụng lâu dài phù hợp cho mọi đối tượng người dùng.\nThiết kế OPPO Glow - màu gradient đẹp mắt\nThoải mái dùng cả ngày với pin 5000 mAh và sạc nhanh 33 W\nHiệu năng ổn định với chip Snapdragon 680', 1, 1, 'Màn hình:\r\n\r\nIPS LCD6.56\"HD+\r\nHệ điều hành:\r\n\r\nAndroid 11\r\nCamera sau:\r\n\r\nChính 13 MP & Phụ 2 MP\r\nCamera trước:\r\n\r\n8 MP\r\nChip:\r\n\r\nSnapdragon 680\r\nRAM:\r\n\r\n6 GB\r\nDung lượng lưu trữ:\r\n\r\n128 GB\r\nSIM:\r\n\r\n2 Nano SIMHỗ trợ 4G\r\nPin, Sạc:\r\n\r\n5000 mAh33 W', 0, 0.0),
(9, 'Điện thoại OPPO A57 128GB', 4290000.00, 100, 'thumb-OPPO A57 4GB 128GB.jpg,couple Oppo A57 12GB.png,Oppo A57 4G 128G blue.jpg,Oppo A57 128Gb .png,oppo a57 128G.jpg,oppo a57 4g.jpg', 0.00, 0, 0, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'OPPO đã bổ sung thêm vào dòng sản phẩm OPPO A giá rẻ một thiết bị mới có tên OPPO A57 128GB. Khác với mẫu A57 5G đã được ra mắt trước đó, điện thoại dòng A mới có màn hình HD+, camera chính 13 MP và pin 5000 mAh.\nThiết kế trẻ trung\nHiệu năng ổn định trong tầm giá\nHỗ trợ chụp ảnh quay phim', 1, 1, 'Màn hình:\r\n\r\nIPS LCD6.56\"HD+\r\nHệ điều hành:\r\n\r\nAndroid 12\r\nCamera sau:\r\n\r\nChính 13 MP & Phụ 2 MP\r\nCamera trước:\r\n\r\n8 MP\r\nChip:\r\n\r\nMediaTek Helio G35\r\nRAM:\r\n\r\n4 GB\r\nDung lượng lưu trữ:\r\n\r\n128 GB\r\nSIM:\r\n\r\n2 Nano SIMHỗ trợ 4G\r\nPin, Sạc:\r\n\r\n5000 mAh33 W', 0, 0.0),
(10, 'Điện thoại OPPO A17', 3790000.00, 99, 'oppo-a-17t_i_xu_ng_30__3.png,thumb-oppo-a-17b1ppr0nazrpqahyt.jpg,oppo a17 dep khong can cho che.png,oppo a17 blue tao lao.png,oppo 17 dep khong phai che.png,oppo a17 chuan dep blue.png', 0.00, 0, 2, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'Dường như OPPO đang ngày càng quan tâm đến trải nghiệm của người dùng, điều này được minh chứng qua nhiều dòng điện thoại của hãng trong đó có OPPO A17, máy sở hữu màn hình kích thước lớn, camera 50 MP đi cùng viên pin 5000 mAh với thời lượng dùng bền bỉ.\nDiện mạo mới lạ và độc đáo\nBắt trọn khoảnh khắc đẹp với độ chi tiết cao\nKhông gian hiển thị rộng lớn\nMang đến sự ổn định nhờ chipset MediaTek\nThoải mái sử dụng cả ngày nhờ pin lớn', 1, 1, 'Màn hình:\r\n\r\nIPS LCD6.56\"HD+\r\nHệ điều hành:\r\n\r\nAndroid 12\r\nCamera sau:\r\n\r\nChính 50 MP & Phụ 0.3 MP\r\nCamera trước:\r\n\r\n5 MP\r\nChip:\r\n\r\nMediaTek Helio G35\r\nRAM:\r\n\r\n4 GB\r\nDung lượng lưu trữ:\r\n\r\n64 GB\r\nSIM:\r\n\r\n2 Nano SIMHỗ trợ 4G\r\nPin, Sạc:\r\n\r\n5000 mAh10 W', 0, 0.0),
(11, 'Điện thoại OPPO A17K', 3200000.00, 94, 'thumb-oppo a17k dien thoai thong minh.png,t_i_xu_ng_62__1.png,oppo a17k.png,combo_a17k_-_navy_-_cmyk.jpg,oppo a17 mau kim rat dep.png,Oppo A17 gia re uu dai.jpg', 0.00, 0, 1, '2023-03-12 03:21:43', '2023-03-14 15:25:01', 'OPPO A17K là chiếc điện thoại được kế thừa thiết kế tinh tế của OPPO A16K, được nâng cấp về dung lượng pin, đồng thời cũng sở hữu màn hình chi tiết cùng một hiệu năng ổn định được nhà OPPO cho ra mắt vào những tháng cuối năm 2022.\r\nSử dụng thả ga với viên pin lớn, hiệu năng mượt mà\r\nTrải nghiệm tuyệt hơn trên màn hình lớn\r\nChụp ảnh rõ nét nhờ camera AI\r\n', 1, 11, 'Màn hình:\r\n\r\nIPS LCD6.56\"HD+\r\nHệ điều hành:\r\n\r\nAndroid 12\r\nCamera sau:\r\n\r\n8 MP\r\nCamera trước:\r\n\r\n5 MP\r\nChip:\r\n\r\nMediaTek Helio G35\r\nRAM:\r\n\r\n3 GB\r\nDung lượng lưu trữ:\r\n\r\n64 GB\r\nSIM:\r\n\r\n2 Nano SIMHỗ trợ 4G\r\nPin, Sạc:\r\n\r\n5000 mAh10 W', 0, 0.0),
(12, 'OPPO Find X3 Pro 5G', 18790000.00, 98, 'thumb-oppo-find-x3-pro-5g-3_2.jpg,Oppo Fnd X3 Pro chuan dep phai manh.jpg,Oppo Find X pro 5g dep mat.jpg,Oppo Find X3 Pro ket hop cung voi nhau.jpg,Oppo Find x3 pro 5g chuan dep.jpg,Oppo find x3 pro 5g.jpg', 10.00, 0, 5, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'Đánh giá Oppo Find X3 Pro 5G – Hiệu năng dẫn đầu, màn hình chiếm trọn\r\nFind X là dòng sản phẩm được OPPO chăm chút nhiều nhất, đặc biệt là những công nghệ hoàn toàn hiện đại. Bằng chứng Find X3 Pro mang đến vẻ ngoài mới, camera selfie được ẩn dưới màn hình, cùng cấu hình mạnh mẽ đến từ chip Snapdragon 865.\r\nHoàn thiện nguyên khối, màn hình 2K rực rỡ\r\nCấu hình mạnh mẽ với bộ vi xử lý Snapdragon 888, 12GB RAM và 256GB bộ nhớ trong\r\nCụm bốn camera sau, cho phép chụp góc siêu rộng, camera selfie ẩn dưới màn hình\r\nViên pin dung lượng 4500 mAh, sạc nhanh 65W\r\nĐiện thoại Oppo Find X3 Pro giá bao nhiêu tiền?\r\nMua OPPO Find X3 Pro 5G chính hãng, giá rẻ tại CellphoneS\r\n', 1, 2, 'Kích thước màn hình\r\n6.7 inches\r\nCông nghệ màn hình\r\nAMOLED\r\nCamera sau\r\nCamera chính: 50 MP, f/1.8, 1/1.56\", 1.0µm, PDAF, OIS\r\nCamera tele: 13 MP, f/2.4, 52mm PDAF, zoom quang 5x\r\nCamera góc rộng: 50 MP, f/2.2, 110˚, 1/1.56\", 1.0µm, omnidirectional PDAF\r\nCamera macro: 3 MP, f/3.0\r\nCamera trước\r\n32 MP, f/2.4, 26mm (wide), 1/2.8\", 0.8µm\r\nChipset\r\nSnapdragon 888 (5 nm)\r\nCông nghệ màn hình\r\nAMOLED\r\nDung lượng RAM\r\n12 GB\r\nBộ nhớ trong\r\n\r\n256 GB\r\nPin\r\n\r\n4500mAh', 0, 0.0),
(13, 'OPPO Find X', 11990000.00, 100, 'thumb-find_x.jpg,oppo-find-x-dep.jpg,find-x-1_1.jpg,find-x-6.jpg,find-x-5.jpg,oppo-find-x_1.jpg', 0.00, 0, 0, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'OPPO Find X Chính hãng\r\nSau sự thành công của OPPO F7 Youth, OPPO Find 7, hãng điện thoại OPPO đang từng bước khẳng định vị thế của một trong những hãng sản xuất smartphone hàng đầu thế giới. Với chiếc Find X sở hữu thiết kế đột phá, công ty này quyết tâm khẳng định họ hoàn toàn có thể sáng tạo hơn cả Apple lẫn Samsung.\r\n\r\nNgoài ra, khách hàng có thể tham khảo điện thoại Oppo Find X2 với nhiều nâng cấp về cấu hình, camera.\r\nThiết kế OPPO Find X mang lại sự khác biệt\r\nMàn hình OPPO Find X đem đến trải nghiệm hình ảnh sống động\r\nHiệu năng OPPO Find X thuộc top đầu thị trường\r\nOPPO Find X tích hợp công nghệ mở khóa bằng gương mặt hiện đại\r\nOPPO Find X có thời lượng pin ấn tượng và thời gian sạc cũng rất nhanh\r\nCamera OPPO Find X lưu giữ chân thực mọi khoảnh khắc\r\n', 1, 2, 'Công nghệ màn hình\r\n\r\nCảm ứng điện dung AMOLED, 16 triệu màu\r\nKích thước màn hình\r\n\r\n6.42 inches\r\nCamera sau\r\n\r\n16 MP (f/2.0, PDAF, OIS) + 20 MP (f/2.0), tự động lấy nét nhận diện theo giai đoạn, LED flash kép (2 tone)\r\nCamera trước\r\n\r\n2160p@30fps\r\nChipset\r\n\r\nQualcomm SDM845 Snapdragon 845\r\nBộ nhớ trong\r\n\r\n256 GB\r\nPin\r\n\r\nLi-ion 3730 mAh\r\nThẻ SIM\r\n\r\n2 SIM (Nano-SIM)\r\nHệ điều hành\r\n\r\n8.1 (Oreo)\r\nĐộ phân giải màn hình\r\n\r\n1080 x 2340 pixels (FullHD+)\r\nTrọng lượng\r\n\r\n186 g (6.56 oz)\r\nCảm biến\r\n\r\nFace ID, gia tốc, con quay hồi chuyển, khoảng cách, la bàn', 0, 0.0),
(14, 'OPPO Find X2', 18990000.00, 100, 'thumb-637191049692122812_oppo-find-x2-xanh-1.png,637194498955419635_oppo-find-x2-den-3.png,637194498955464088_oppo-find-x2-den-4.png,637194500600555695_oppo-find-x2-xanh-3.png,Oppo Find X dep gia re.jpg,637194500601105652_oppo-find-x2-xanh-4.png', 10.00, 0, 1, '2023-03-12 09:21:43', '2023-03-14 15:25:01', 'Oppo Find X2 – Hiệu năng đỉnh cao, màn hình chiếm trọn mặt trước\r\nOppo Find X2 và Find X2 Pro là chiếc điện thoại thuộc phân khúc cao cấp vừa được Oppo ra mắt, tiếp nối sự thành công vang dội của người tiền nhiệm Oppo Find X. Đây là mẫu sản phẩm điện thoại Oppo được thừa hưởng những công nghệ mới và tốt nhất ở thời điểm hiện tại so với các đối thủ cùng phân khúc. Ngoài ra, bạn cũng có thể tham khảo điện thoại Oppo Find X3 với nhiều nâng cấp về cấu hình, thiết kế, camera cũng như dung lượng pin.\r\nThiết kế chuyển màu nổi bật, cho cảm giác cực kì nhẹ nhàng\r\nMàn hình OLED 6,7 inchQuad-HD+ cho khả năng hiển thị sắc nét, sống động\r\nCấu hình mạnh mẽ với vi xử lý Snapdragon 865 đi kèm 12GB RAM\r\nDung lượng pin lên đến 4200mAh, có khả năng cho thiết bị khác\r\nBa camera sau 48 MP + 13 MP + 12MP cùng camera selfie 32 MP\r\nMua điện thoại Oppo Find X2 chính hãng, giá rẻ nhất tại CellphoneS', 1, 2, 'Kích thước màn hình\r\n\r\n6.7 inches\r\nCông nghệ màn hình\r\n\r\nAMOLED\r\nCamera sau\r\n\r\nChính 48 MP & Phụ 13 MP, 12 MP\r\nCamera trước\r\n\r\n32 MP\r\nChipset\r\n\r\nQualcomm Snapdragon 865\r\nCông nghệ màn hình\r\n\r\nAmoled\r\nDung lượng RAM\r\n\r\n12 GB\r\nBộ nhớ trong\r\n\r\n256 GB\r\nPin\r\n\r\n4200 mAh Li-Ion, Hỗ trợ sạc nhanh\r\nThẻ SIM\r\n\r\n2 SIM (Nano-SIM)\r\nHệ điều hành\r\n\r\nAndroid 10.0 , ColorOS 7.0\r\nĐộ phân giải màn hình\r\n\r\n3168 x 1440 pixel\r\nTính năng màn hình\r\n\r\nMàn hình 2K, Tần số quét 120 Hz, Kính cường lực Corning Gorilla Glass 6\r\nCảm biến\r\n\r\n- Vân tay ẩn trong màn hình: Hỗ trợ\r\n- Cảm biến: Cảm biến nhiệt độ màu, Cảm biến ánh sáng, Cảm biến tiệm cận, La Bàn, Con Quay Hồi Chuyển.', 0, 0.0),
(17, 'Xiaomi Redmi 10C', 3590000.00, 98, 'thumb-xiaomi-redmi-10c.jpeg,xiaomi-redmi-10c-1.jpeg, xiaomi-redmi-10c-2.jpeg,xiaomi-redmi-10c-3.jpeg, xiaomi-redmi-10c-4.jpeg', 10.00, 0, 1, '2023-03-13 20:28:03', '2023-03-14 15:25:01', 'Xiaomi Redmi 10C 64GB ra mắt với một cấu hình mạnh mẽ nhờ trang bị con chip 6 nm đến từ Qualcomm, màn hình hiển thị đẹp mắt, pin đáp ứng nhu cầu sử dụng cả ngày, hứa hẹn mang đến trải nghiệm tuyệt vời so với mức giá mà nó trang bị.', 4, 13, 'Màn hình: IPS LCD6.71\"HD+ \r\nHệ điều hành: Android 11 \r\nCamera sau: Chính 50 MP & Phụ 2 MP \r\nCamera trước: 5 MP \r\nChip: Snapdragon 680 \r\nRAM: 4 GB \r\nDung lượng lưu trữ: 64 GB \r\nSIM: 2 Nano SIM\r\nHỗ trợ 4G Pin\r\nSạc: 5000 mAh18 W', 0, 0.0),
(18, 'Xiaomi Redmi Note 11', 4390000.00, 98, 'thumb-xiaomi-redmi-note-11.jpeg,xiaomi-redmi-note-11-1.jpeg, xiaomi-redmi-note-11-2.jpeg,xiaomi-redmi-note-11-3.jpeg,xiaomi-redmi-note-11-4.jpeg                                                                ', 10.00, 0, 0, '2023-03-13 20:32:03', '2023-03-14 15:25:01', 'Redmi Note 11 (6GB/128GB) vừa được Xiaomi cho ra mắt, được xem là chiếc smartphone có giá tầm trung ấn tượng, với 1 cấu hình mạnh, cụm camera xịn sò, pin khỏe, sạc nhanh mà giá lại rất phải chăng.Thiết kế bo cong đậm chất Xiaomi,Hiệu năng mạnh mẽ với chip Snapdragon,Màn hình sắc nét, chiến game mượt mà, Bắt trọn từng khoảnh khắc với cụm camera xịn sò.', 4, 13, 'Màn hình: AMOLED6.43\"Full HD+ \r\nHệ điều hành: Android 11      \r\nCamera sau: Chính 50 MP & Phụ 8 MP, 2 MP, 2 MP      \r\nCamera trước: 13 MP      \r\nChip: Snapdragon 680     \r\nRAM: 6 GB       \r\nDung lượng lưu trữ: 128 GB       \r\nSIM: 2 Nano SIM\r\nHỗ trợ 4G      \r\nPin, Sạc: 5000 mAh33 W', 0, 0.0),
(19, 'Xiaomi Redmi Note 11 Pro', 6190000.00, 98, 'thumb-xiaomi-redmi-note-11-pro.jpeg, xiaomi-redmi-note-11-pro-1.jpeg, xiaomi-redmi-note-11-pro-2.jpeg, xiaomi-redmi-note-11-pro-3.jpeg, xiaomi-redmi-note-11-pro-4.jpeg        ', 10.00, 0, 0, '2023-03-13 20:35:08', '2023-03-14 15:25:01', 'Xiaomi Redmi Note 11 Pro 4G mang trong mình khá nhiều những nâng cấp cực kì sáng giá. Là chiếc điện thoại có màn hình lớn, tần số quét 120 Hz, hiệu năng ổn định cùng một viên pin siêu trâu.Thiết kế cứng cáp, cầm nắm rất đầm tay,Hiệu năng ổn định cho mọi tác vụ,Camera AI đến 108 MP,Pin lớn, sạc siêu nhanh.', 4, 13, 'Màn hình: AMOLED6.67\"Full HD+ \r\nHệ điều hành: Android 11 \r\nCamera sau: Chính 108 MP & Phụ 8 MP, 2 MP, 2 MP \r\nCamera trước: 16 MP \r\nChip: MediaTek Helio G96 \r\nRAM: 8 GB \r\nDung lượng lưu trữ: 128 GB \r\nSIM: 2 Nano SIM (SIM 2 chung khe thẻ nhớ)\r\nHỗ trợ 4G Pin\r\nSạc: 5000 mAh67 W', 0, 0.0),
(20, 'Xiaomi Redmi Note 11S', 5690000.00, 99, 'thumb-xiaomi-redmi-note-11s.jpeg,xiaomi-redmi-note-11s-1.jpeg,xiaomi-redmi-note-11s-2.jpeg,xiaomi-redmi-note-11s-3.jpeg, xiaomi-redmi-note-11s-4.jpeg         ', 10.00, 0, 0, '2023-03-13 20:37:08', '2023-03-14 15:25:01', 'Điện thoại Xiaomi Redmi Note 11S sẵn sàng đem đến cho bạn những trải nghiệm vô cùng hoàn hảo về chơi game, các tác vụ sử dụng hằng ngày hay sự ấn tượng từ vẻ đẹp bên ngoài.Ấn tượng với màn hình AMOLED 6.43 inch,Ảnh chụp đẹp và siêu rõ nét với hệ thống bốn camera AI 108 MP,Hiệu năng ổn định với MediaTek Helio G96,Thiết kế tối giản nhưng vẫn năng động và mạnh mẽ.', 4, 13, 'Màn hình: AMOLED6.43\"Full HD+ \r\nHệ điều hành: Android 11 \r\nCamera sau: Chính 108 MP & Phụ 8 MP, 2 MP, 2 MP \r\nCamera trước: 16 MP \r\nChip: MediaTek Helio G96 \r\nRAM: 8 GB \r\nDung lượng lưu trữ: 128 GB \r\nSIM: 2 Nano SIM\r\nHỗ trợ 4G Pin, \r\nSạc: 5000 mAh33 W', 0, 0.0),
(21, 'Xiaomi Redmi 10', 4100000.00, 99, 'thumb-xiaomi-redmi-10-2022-xanh.jpeg, xiaomi-redmi-10-2022-xanh-1.jpeg, xiaomi-redmi-10-2022-xanh-2.jpeg, xiaomi-redmi-10-2022-xanh-3.jpeg, xiaomi-redmi-10-2022-xanh-4.jpeg     ', 10.00, 0, 0, '2023-03-13 20:39:08', '2023-03-14 15:25:01', 'Xiaomi Redmi 10 (2022) được ra mắt vào tháng 05/2022 với những nâng cấp về thuật toán xử lý khi chụp ảnh trên camera nhằm giúp khách hàng có được những bức hình chất lượng hơn trên một thiết bị thuộc phân khúc giá rẻ.Chụp ảnh chất lượng, Màn hình hiển thị sống động, Hiệu suất mạnh mẽ nhờ chipset gaming đến từ MediaTek, Thời lượng sử dụng dài lâu.', 4, 13, 'Màn hình: IPS LCD6.5\"Full HD+ \r\nHệ điều hành: Android 11 \r\nCamera sau: Chính 50 MP & Phụ 8 MP, 2 MP, 2 MP \r\nCamera trước: 8 MP \r\nChip: MediaTek Helio G88 \r\nRAM: 4 GB \r\nDung lượng lưu trữ: 128 GB \r\nSIM: 2 Nano SIM (SIM 2 chung khe thẻ nhớ)\r\nHỗ trợ 4G Pin \r\nSạc: 5000 mAh18 W', 0, 0.0),
(22, 'Xiaomi 12T 5G', 11390000.00, 99, 'thumb-xiaomi-12t-glr-den.jpeg, xiaomi-12t-glr-den-1.jpeg, xiaomi-12t-glr-den-2.jpeg, xiaomi-12t-glr-den-3.jpeg, xiaomi-12t-glr-den-4.jpeg      ', 10.00, 0, 0, '2023-03-13 20:42:54', '2023-03-14 15:25:01', 'Xiaomi 12T 5G 256GB là smartphone đầu tiên trên thế giới trang bị con chip Dimensity 8100 Ultra nên máy thu hút được khá nhiều sự chú ý vào thời điểm ra mắt, bộ vi xử lý này không chỉ có hiệu năng mạnh mẽ mà nó còn tối ưu được giá thành cho thiết bị, điều này giúp 12T trở thành chiếc điện thoại quốc dân cực kỳ đáng sắm.', 4, 14, 'Màn hình: AMOLED6.67\"1.5K \r\nHệ điều hành: Android 12 \r\nCamera sau: Chính 108 MP & Phụ 8 MP, 2 MP \r\nCamera trước: 20 MP \r\nChip: MediaTek Dimensity 8100 Ultra 8 nhân \r\nRAM: 8 GB \r\nDung lượng lưu trữ: 256 GB \r\nSIM: 2 Nano SIM\r\nHỗ trợ 5G Pin\r\nSạc: 5000 mAh120 W', 0, 0.0),
(23, 'Xiaomi 11T 5G', 8990000.00, 99, 'thumb-xiaomi-11t-xanh-duong.jpeg, xiaomi-11t-xanh-duong-1.jpeg, xiaomi-11t-xanh-duong-2.jpeg, xiaomi-11t-xanh-duong-3.jpeg, xiaomi-11t-xanh-duong-4.jpeg  ', 10.00, 0, 0, '2023-03-13 20:45:54', '2023-03-14 15:25:01', 'Xiaomi 11T 5G sở hữu màn hình AMOLED, viên pin siêu khủng cùng camera độ phân giải 108 MP, điện thoại Xiaomi sẽ đáp ứng mọi nhu cầu sử dụng của bạn, từ giải trí đến làm việc đều vô cùng mượt mà. Cho ra những tác phẩm đầy chân thật với camera 108 MP, Sẵn sàng “chiến” mọi tựa game, Màn hình lớn, độ phân giải cao cho hình ảnh sắc nét.\r\n', 4, 14, 'Màn hình: AMOLED6.67\"Full HD+ \r\nHệ điều hành: Android 11 \r\nCamera sau: Chính 108 MP & Phụ 8 MP, 5 MP \r\nCamera trước: 16 MP \r\nChip: MediaTek Dimensity 1200 \r\nRAM: 8 GB \r\nDung lượng lưu trữ: 256 GB \r\nSIM: 2 Nano SIM\r\nHỗ trợ 5G Pin\r\nSạc: 5000 mAh67 W', 0, 0.0),
(24, 'Xiaomi 13 Pro 5G', 29990000.00, 100, 'thumb-xiaomi-13-pro-trang.jpeg, xiaomi-13-pro-trang-1.jpeg, xiaomi-13-pro-trang-2.jpeg, xiaomi-13-pro-trang-3.jpeg, xiaomi-13-pro-trang-4.jpeg  ', 10.00, 0, 0, '2023-03-13 20:48:54', '2023-03-14 15:25:01', 'Sau biết bao thông tin rò rỉ Xiaomi 13 Pro cũng đã chính thức giới thiệu tại thị trường Việt Nam với sự háo hức đến từ các Mi fan trong nước, đây dự kiến sẽ là mẫu điện thoại quốc dân cho năm 2023 bởi máy sở hữu con chip Snapdragon 8 Gen 2 mạnh mẽ cùng với đó là sự cộng tác với nhà Leica để khiến mọi người dùng đam mê nhiếp ảnh mê hoặc.', 4, 14, 'Màn hình: AMOLED6.73\"Quad HD+ (2K+) \r\nHệ điều hành: Android 13 \r\nCamera sau: Chính 50 MP & Phụ 50 MP, 50 MP \r\nCamera trước: 32 MP \r\nChip: Snapdragon 8 Gen 2 8 nhân \r\nRAM: 12 GB \r\nDung lượng lưu trữ: 256 GB \r\nSIM: 2 Nano SIM\r\nHỗ trợ 5G Pin \r\nSạc: 4820 mAh120 W', 0, 0.0),
(25, 'Xiaomi 12 5G', 11690000.00, 100, 'thumb-xiaomi-mi-12.jpeg, xiaomi-mi-12-1.jpeg, xiaomi-mi-12-2.jpeg, xiaomi-mi-12-3.jpeg, xiaomi-mi-12-4.jpeg      ', 10.00, 0, 0, '2023-03-13 20:50:54', '2023-03-14 15:25:01', 'Điện thoại Xiaomi đang dần khẳng định chỗ đứng của mình trong phân khúc flagship bằng việc ra mắt Xiaomi 12 với bộ thông số ấn tượng, máy có một thiết kế gọn gàng, hiệu năng mạnh mẽ, màn hình hiển thị chi tiết cùng khả năng chụp ảnh sắc nét nhờ trang bị ống kính đến từ Sony.', 4, 14, 'Màn hình: AMOLED6.28\"Full HD+ \r\nHệ điều hành: Android 12 \r\nCamera sau: Chính 50 MP & Phụ 13 MP, 5 MP \r\nCamera trước: 32 MP \r\nChip: Snapdragon 8 Gen 1 \r\nRAM: 8 GB \r\nDung lượng lưu trữ: 256 GB \r\nSIM: 2 Nano SIM\r\nHỗ trợ 5G Pin\r\nSạc: 4500 mAh67 W', 0, 0.0),
(26, 'Xiaomi 11 Lite 5G NE', 7090000.00, 100, 'thumb-xiaomi-11-lite-5g-ne.jpeg, xiaomi-11-lite-5g-ne-1.jpeg, xiaomi-11-lite-5g-ne-2.jpeg, xiaomi-11-lite-5g-ne-3.jpeg, xiaomi-11-lite-5g-ne-4.jpeg  ', 10.00, 0, 0, '2023-03-13 20:52:54', '2023-03-14 15:25:01', 'Xiaomi 11 Lite 5G NE một phiên bản có ngoại hình rất giống với Xiaomi Mi 11 Lite được ra mắt trước đây. Chiếc smartphone này của Xiaomi mang trong mình một hiệu năng ổn định, thiết kế sang trọng và màn hình lớn đáp ứng tốt các tác vụ hằng ngày của bạn một cách dễ dàng.', 4, 14, 'Màn hình: AMOLED6.55\"Full HD+ \r\nHệ điều hành: Android 11 \r\nCamera sau: Chính 64 MP & Phụ 8 MP, 5 MP \r\nCamera trước: 20 MP \r\nChip: Snapdragon 778G 5G \r\nRAM: 8 GB \r\nDung lượng lưu trữ: 128 GB \r\nSIM: 2 Nano SIM (SIM 2 chung khe thẻ nhớ)\r\nHỗ trợ 5G Pin \r\nSạc: 4250 mAh33 W', 0, 0.0),
(27, 'Xiaomi Poco M4 Pro 5G', 3790000.00, 100, 'thumb-poco-m4-pro-5g.jpeg, xiaomi-poco-m4-pro-1.jpeg, xiaomi-poco-m4-pro-2.jpeg, xiaomi-poco-m4-pro-3.jpeg, xiaomi-poco-m4-pro-4.jpeg   ', 10.00, 0, 0, '2023-03-13 20:54:35', '2023-03-14 15:25:01', 'Poco M4 Pro 5G là một trong những chiếc Smartphone tầm trung đang nhận được nhiều sự quan tâm từ người dùng. Sản phẩm không chỉ có diện mạo đẹp mắt, chiếc máy này còn được trang bị nhiều công nghệ ấn tượng.Poco M4 Pro 5G có thiết kế hiện đại, mặt lưng bóng loáng nổi bật, sở hữu màn hình có kích thước khá lớn , được trang bị con chip Dimensity 810 khá mạnh mẽ.\r\n', 4, 15, 'Hệ điều hành: Android 11, MIUI 12.5 Chipset: MediaTek Dimensity 810 5G (6 nm) Độ phân giải: 1080 x 2400 pixels \r\nMàn hình rộng: 6.6 inches \r\nCamera sau: 50MP + 8MP \r\nRAM: 6 GB \r\nBộ nhớ trong ( Rom): 128GB \r\nCamera trước: 16 MP, f/2.5 \r\nDung lượng pin: 5000 mAh', 0, 0.0),
(28, 'Xiaomi Poco F3', 6990000.00, 100, 'thumb-xiaomi-poco-f3.jpeg, xiaomi-poco-f3-1.jpeg, xiaomi-poco-f3-2.jpeg, xiaomi-poco-f3-3.jpeg, xiaomi-poco-f3-4.jpeg      ', 10.00, 0, 1, '2023-03-13 20:56:35', '2023-03-14 15:25:01', 'Xiaomi Poco F3, còn gọi là Poco F3 chính là phiên bản quốc tế được phân phối toàn cầu của mẫu smartphone tầm trung Xiaomi Redmi K40. Máy sở hữu thiết kế rất sang trọng nhiều phá cách, kết hợp với cấu hình - tính năng vô cùng mạnh mẽ: chip Snapdragon 870, màn hình tần số quét 120Hz, kết nối mạng 5G, sạc nhanh 33W...', 4, 15, 'Hệ điều hành: Android 11, MIUI 12 Chipset: Qualcomm SM8250-AC Snapdragon 870 5G (7 nm) \r\nĐộ phân giải: 1080 x 2400 pixels \r\nMàn hình rộng: 6.67 inches \r\nCamera sau: 3 camera: 48MP + 8MP + 5MP \r\nRAM: 8 GB \r\nBộ nhớ trong ( Rom): 256GB \r\nCamera trước: 20 MP, (wide) \r\nDung lượng pin: 4520 mAh', 0, 0.0),
(29, 'Xiaomi POCO X3 Pro', 6790000.00, 100, 'thumb-xiaomi-poco-x3-pro.jpeg, Xiaomi-Poco-X3-Pro-1.jpeg, Xiaomi-Poco-X3-Pro-2.jpeg, Xiaomi-Poco-X3-Pro-3.jpeg, Xiaomi-Poco-X3-Pro-4.jpeg    ', 10.00, 0, 0, '2023-03-13 20:58:35', '2023-03-14 15:25:01', 'Xiaomi POCO X3 Pro 256GB là chiếc smartphone mạnh mẽ nhất, ngoại hình hoàn thiện tinh xảo nhất trong loạt smartphone tầm giá 6 triệu đồng, Màn hình Xiaomi POCO X3 Pro: Nổi bật với tần số 120Hz, Ấn tượng với cụm camera độc đáo, Mạnh mẽ, vượt trội với Snapdragon 860\r\n', 4, 15, 'Hệ điều hành: Android 11, MIUI 12 for POCO \r\nChipset: Snapdragon 860 \r\nĐộ phân giải: 1080 x 2400 pixels \r\nMàn hình rộng: 6.67 inches \r\nCamera sau: 4 camera: 48MP + 8MP + 2MP + 2MP \r\nRAM: 6 GB \r\nBộ nhớ trong ( Rom): 128 GB \r\nCamera trước: 20 MP, f/2.2, (wide), 1/3.4\", 0.8µm \r\nDung lượng pin: 5160 mAh', 0, 0.0),
(30, 'Xiaomi Poco X4 Pro 5G', 5990000.00, 100, 'thumb-xiaomi-poco-x4-pro.jpeg, xiaomi-poco-x4-pro-1.jpeg, xiaomi-poco-x4-pro-2.jpeg, xiaomi-poco-x4-pro-3.jpeg, xiaomi-poco-x4-pro-4.jpeg  ', 10.00, 0, 0, '2023-03-13 21:00:35', '2023-03-14 15:25:01', 'Xiaomi Poco X4 Pro 5G là chiếc smartphone tầm trung vừa được ra mắt trong khuôn khổ MCW 2022 vừa qua. Đây có lẽ là chiếc smartphone giá rẻ sở hữu màn hình OLED tần số quét 120Hz hiếm hoi trong phân khúc. Ngoài ra máy còn sở hữu các thông số cấu hình cực mạnh.', 4, 15, 'Hệ điều hành: Android 11, MIUI 13 for POCO \r\nChipset: Qualcomm SM6375 Snapdragon 695 5G (6 nm) \r\nĐộ phân giải: 1080 x 2400 pixels \r\nMàn hình rộng: 6.67 inches \r\nCamera sau: 108MP + 8MP + 2MP \r\nRAM: 8 GB \r\nBộ nhớ trong ( Rom): 256GB \r\nCamera trước: 16 MP, f/2.4, (wide) \r\nDung lượng pin: 5000 mAh', 0, 0.0),
(31, 'Xiaomi Poco F4', 7590000.00, 100, 'thumb-xiaomi-poco-f4.jpeg, xiaomi-poco-f4-1.jpeg, xiaomi-poco-f4-2.jpeg, xiaomi-poco-f4-3.jpeg, xiaomi-poco-f4-4.jpeg      ', 10.00, 0, 0, '2023-03-13 21:02:35', '2023-03-14 15:25:01', 'Xiaomi Poco F4 - Smartphone tầm trung, cận cao cấp nhận được sự chào đón nồng nhiệt từ người dùng. Với cấu hình mạnh mẽ, màn hình hiển thị rực rỡ, pin khủng và nhiều công nghệ thông minh, đi kèm đó là giá bán khá hợp lý. Xiaomi Poco F4 nhanh chóng trở thành một cái tên khá HOT và được săn đón nhiều!', 4, 15, 'Hệ điều hành: Android 10; MIUI 11 \r\nChipset: Snapdragon 870 \r\nĐộ phân giải: 1080 x 2400 pixels \r\nMàn hình rộng: 6.67 inches \r\nCamera sau: 3 camera: 64MP + 8MP +5MP \r\nRAM: 6 GB \r\nBộ nhớ trong ( Rom): 128 GB \r\nCamera trước: 20MP \r\nDung lượng pin: 4520 mAh', 0, 0.0),
(32, 'Xiaomi Poco X3 GT', 7290000.00, 100, 'thumb-xiaomi-poco-x3-gt.jpeg, xiaomi-poco-x3-gt-1.jpeg, xiaomi-poco-x3-gt-2.png, xiaomi-poco-x3-gt-3.jpeg, xiaomi-poco-x3-gt-4.jpeg           ', 10.00, 0, 0, '2023-03-13 21:05:35', '2023-03-14 15:25:01', 'POCO – thương hiệu con của Xiaomi đã cho ra mắt một mẫu smartphone mới mang tên Xiaomi POCO X3 GT, được biết đây là phiên bản đổi tên của Redmi Note 10 Pro 5G máy có thiết kế nguyên khối, mặt lưng độc đáo với hiệu ứng đổi màu khá đẹp mắt.', 4, 15, 'Màn hình: IPS LCD6.6\"Full HD+ \r\nHệ điều hành: Android 11 \r\nCamera sau: Chính 64 MP & Phụ 8 MP, 2 MP \r\nCamera trước: 16 MP \r\nChip: MediaTek Dimensity 1100 \r\nRAM: 8 GB \r\nDung lượng lưu trữ: 256 GB \r\nSIM: 2 Nano SIM\r\nHỗ trợ 5G Pin, \r\nSạc: 5000 mAh67 W', 0, 0.0),
(44, 'Cây Lộc Vừng', 799000.00, 99, 'thumb-locvung1.jpg,thumb-locvung2.jpg,thumb-locvung3.jpg,thumb-locvung4.jpg,thumb-locvung5.jpg', 5.00, 0, 3, '2024-11-26 16:16:32', '2024-11-27 01:33:32', 'Cây thuộc dòng cây bản địa của các vùng đất ẩm ven biển Nam Á và Bắc Úc, từ Afghanistan đến Philippin và Queensland. Ở Việt Nam cây hiện nay cũng được trồng ở khắp mọi nơi từ Bắc vào Nam và ra tận Côn Đảo.\r\nThuộc dòng cây thân gỗ sống lâu năm, chắc khỏe, dễ sống với sức phát triển mạnh. Cây có 3 loại là Lộc Vừng hoa trắng, Lộc Vừng hoa đỏ và Rau Vừng.\r\nCác loại cây Lộc Vừng\r\nNhư giới thiệu bên trên thì cây ở Việt Nam có 3 loại là: Hoa đỏ, hoa trắng và rau vừng.', 65, 4, '<p>Lộc Vừng hoa đỏ\r\nLà một trong những loại phổ biến nhất ở nước ta, mà bạn có thể dễ dàng bắt gặp. Vì cây có hoa màu đỏ thành chùm dài như những bánh pháo nhỏ tượng trưng cho nhà có hỷ sự vì thế mà cây được lựa chọn trồng nhiều nhất.</p>\r\n<p>Lộc Vừng hoa trắng\r\nLoại này sẽ ít gặp hơn và không được phố biến. Chủ yếu dành cho những người thích siêu tầm để tăng thêm tính độc lạ cho khu vườn.</p>\r\n<p>Cây Rau Vừng\r\nCây có lá và hình dạng giống như lộc vừng hoa đỏ và hoa trắng, nhưng tuy nhiên cây có một đặc điểm là ra quả từ cành thay vì ra quả từ hoa.</p>', 0, 0.0),
(45, 'iPhone 14 Pro ', 25990000.00, 100, 'thumb-iphone14pr-1.jpg,iphone14pr-2.jpg,iphone14pr-3.jpg,iphone14pr-4.jpg,iphone14pr-5.jpg', 5.00, 0, 4, '2023-03-13 16:16:32', '2023-03-14 18:40:31', 'Mới đây thì chiếc điện thoại iPhone 14 Pro cũng đã được chính thức lộ diện trên toàn cầu và đập tan bao lời đồn đoán bấy lâu nay, bên trong máy sẽ được trang bị con chip hiệu năng khủng cùng sự nâng cấp về camera đến từ nhà Apple.\r\nDiện mạo đẳng cấp dẫn đầu xu thế\r\nTrang bị cụm 3 camera chất lượng\r\nTrải nghiệm nội dung sinh động trên một màn hình chất lượng\r\nNâng cao khả năng xử lý nhờ chipset khủng', 2, 4, 'Màn hình: OLED6.1 \"Super Retina XDR\r\nHệ điều hành: iOS 16\r\nCamera sau: Chính 48 MP & Phụ 12 MP, 12 MP\r\nCamera trước: 12 MP\r\nChip: Apple A16 Bionic\r\nRAM: 6 GB\r\nDung lượng lưu trữ: 256 GB\r\nSIM: 1 Nano SIM & 1 eSIM Hỗ trợ 5G\r\nPin, Sạc: 3200 mAh 20 W', 0, 0.0),
(46, 'iPhone 14 Plus', 17990000.00, 100, 'thumb-iphone14plus-1.jpg,iphone14plus-2.jpg,iphone14plus-3.jpg,iphone14plus-4.jpg,iphone14plus-5.jpg', 5.00, 0, 1, '2023-03-13 16:19:19', '2023-03-14 18:40:31', 'Sau nhiều thế hệ điện thoại của Apple thì cái tên “Plus” cũng đã chính thức trở lại vào năm 2022 và xuất hiện trên chiếc iPhone 14 Plus 128GB, nổi trội với ngoại hình bắt trend cùng màn hình kích thước lớn để đem đến không gian hiển thị tốt hơn cùng cấu hình mạnh mẽ không đổi so với bản tiêu chuẩn.\r\nThân hình thanh mảnh cùng ngoại hình góc cạnh\r\nMàn hình OLED tái hiện nội dung sinh động\r\nDễ dàng bắt trọn mọi khoảnh khắc\r\nHiệu năng cực khủng với Apple A15 Bionic', 2, 4, 'Màn hình: OLED6.7\" Super Retina XDR\r\nHệ điều hành: iOS 16\r\nCamera sau: 2 camera 12 MP\r\nCamera trước: 12 MP\r\nChip: Apple A15 Bionic\r\nRAM: 6 GB\r\nDung lượng lưu trữ: 128 GB\r\nSIM: 1 Nano SIM & 1 eSIMHỗ trợ 5G\r\nPin, Sạc: 4325 mAh20 W', 0, 0.0),
(47, 'iPhone 14 ', 15990000.00, 100, 'thumb-iphone14-1.jpg,iphone14-2.jpg,iphone14-3.jpg,iphone14-4.jpg,iphone14-5.jpg', 5.00, 0, 0, '2023-03-13 16:19:19', '2023-03-14 18:40:31', 'Mới đây thì tại sự kiện ra mắt sản phẩm mới thường niên đến từ nhà Apple thì chiếc điện thoại iPhone 14 256GB cũng đã chính thức lộ diện, thiết bị được nâng cấp toàn diện từ camera cho đến hiệu năng và hầu hết là những thông số hàng đầu trong giới smartphone. \r\nĐẳng cấp thiết kế dẫn đầu xu thế\r\nTrang bị công nghệ màn hình tân tiến\r\nHỗ trợ chụp ảnh quay phim chuẩn điện ảnh\r\nVi xử lý mạnh mẽ đến từ nhà Apple', 2, 4, 'Màn hình: OLED6.1\"Super Retina XDR\r\nHệ điều hành: iOS 16\r\nCamera sau: 2 camera 12 MP\r\nCamera trước: 12 MP\r\nChip: Apple A15 Bionic\r\nRAM: 6 GB\r\nDung lượng lưu trữ: 256 GB\r\nSIM: 1 Nano SIM & 1 eSIMHỗ trợ 5G\r\nPin, Sạc: 3279 mAh 20 W', 0, 0.0),
(48, 'iPhone 13 Pro Max', 24990000.00, 100, 'thumb-iphone13prm-1.jpg,iphone13prm-2.jpg,iphone13prm-3.jpg,iphone13prm-4.jpg,iphone13prm-5.jpg', 5.00, 0, 0, '2023-03-13 16:19:19', '2023-03-14 18:40:31', 'iPhone 13 Pro Max thuộc phân khúc điện thoại cao cấp mà không một iFan nào có thể bỏ qua, với màn hình lớn sắc nét, cấu hình vượt trội, dung lượng lưu trữ \"khủng\", thời gian sử dụng dài, mỗi lần trải nghiệm đều cho bạn cảm giác thỏa mãn đáng ngạc nhiên.\r\nApple A15 Bionic - cấu hình đột phá\r\nTải xuống siêu nhanh cùng mạng 5G\r\nXem nội dung nhiều hơn, rõ nét hơn với màn hình lớn\r\nNâng cấp hệ thống camera \r\nVẻ ngoài sang trọng đặc trưng\r\nDung lượng pin đáp ứng đến 95 giờ nghe nhạc', 2, 5, 'Màn hình: OLED6.7\" Super Retina XDR\r\nHệ điều hành: iOS 15\r\nCamera sau: 3 camera 12 MP\r\nCamera trước: 12 MP\r\nChip: Apple A15 Bionic\r\nRAM: 6 GB\r\nDung lượng lưu trữ: 1 TB\r\nSIM: 1 Nano SIM & 1 eSIMHỗ trợ 5G\r\nPin, Sạc: 4352 mAh 20 W', 0, 0.0),
(49, 'iPhone 13 Pro', 20990000.00, 100, 'thumb-iphone13pro-1.jpg,iphone13pro-2.jpg,iphone13pro-3.jpg,iphone13pro-4.jpg,iphone13pro-5.jpg', 5.00, 0, 0, '2023-03-13 16:19:19', '2023-03-14 18:40:31', 'Cùng trải nghiệm một phiên bản iPhone có bộ nhớ trong lớn nhất từ trước đến nay, \r\ntương tự với các phiên bản khác máy vẫn có một màn hình siêu đẹp cùng hiệu năng vô cùng mạnh mẽ đó chính là iPhone 13 Pro .\r\nHiệu năng tuyệt vời nhờ chip thế hệ mới\r\nKhung hình rực rỡ, tần số quét màn hình 120 Hz\r\nCụm camera thách thức khả năng sáng tạo của bạn\r\nThiết kế sang chảnh, đa sắc màu lựa chọn\r\nCải thiện thời lượng pin thêm 2.5 giờ sử dụng', 2, 5, 'Màn hình: OLED6.1\" Super Retina XDR\r\nHệ điều hành: iOS 15\r\nCamera sau: 3 camera 12 MP\r\nCamera trước: 12 MP\r\nChip: Apple A15 Bionic\r\nRAM: 6 GB\r\nDung lượng lưu trữ: 1 TB\r\nSIM: 1 Nano SIM & 1 eSIMHỗ trợ 5G\r\nPin, Sạc: 3095 mAh20 W', 0, 0.0),
(50, 'iPhone 13 Mini', 15990000.00, 100, 'thumb-iphone13mini-1.jpg,iphone13mini-2.jpg,iphone13mini-3.jpg,iphone13mini-4.jpg,iphone13mini-5.jpg', 5.00, 0, 0, '2023-03-13 16:19:19', '2023-03-14 18:40:31', 'Đánh giá iPhone 13 mini – Phiên bản thu nhỏ hoàn hảo của iPhone 13\r\nTương tự như iPhone 12 Series, iPhone 13 cũng sẽ được trang bị một phiên bản thu nhỏ mang tên iPhone 13 mini. Mẫu iPhone nhỏ gọn với nhiều cải tiến so với iPhone 12 mini tiền nhiệm.\r\nThiết kế nhỏ gọn, khung viền vuông vắn\r\nMàn hình Super Retina XDR\r\nHiệu năng nâng cấp với chip Apple A15 Bionic\r\nDung lượng pin được cải thiện, hỗ trợ sạc nhanh\r\nCamera cảm biến nâng cấp', 2, 5, 'Kích thước màn hình 5.4 inches\r\nCông nghệ màn hình OLED\r\nCamera sau Camera góc rộng: 12MP, f/1.6\r\nCamera góc siêu rộng: 12MP, ƒ/2.4\r\nCamera trước 12MP, f/2.2\r\nChipset Apple A15\r\nDung lượng RAM 4 GB\r\nBộ nhớ trong 128 GB\r\nPin 2406mAh\r\nThẻ SIM 2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành iOS15\r\nĐộ phân giải màn hình 1080 x 2340 pixels (FullHD+)', 0, 0.0),
(51, 'iPhone 13 ', 16990000.00, 100, 'thumb-iphone13-1.jpg,iphone13-2.jpg,iphone13-3.jpg,iphone13-4.jpg,iphone13-5.jpg', 5.00, 0, 0, '2023-03-13 16:19:19', '2023-03-14 18:40:31', 'Apple thỏa mãn sự chờ đón của iFan và người dùng với sự ra mắt của iPhone 13. Dù ngoại hình không có nhiều thay đổi so với iPhone 12 nhưng với cấu hình mạnh mẽ hơn, đặc biệt pin “trâu” hơn và khả năng quay phim chụp ảnh cũng ấn tượng hơn, hứa hẹn mang đến những trải nghiệm thú vị trên phiên bản mới này.\r\nHiệu năng đột phá cùng bộ xử lý Apple A15 Bionic\r\nMàn hình Super Retina XDR sắc nét, siêu sáng\r\nHệ thống camera xuất sắc\r\n“Áo” mới tinh tế hơn\r\nPin khỏe hơn, trải nghiệm tốt hơn', 2, 5, 'Màn hình: OLED6.1\"Super Retina XDR\r\nHệ điều hành: iOS 15\r\nCamera sau: 2 camera 12 MP\r\nCamera trước: 12 MP\r\nChip: Apple A15 Bionic\r\nRAM: 4 GB\r\nDung lượng lưu trữ: 256 GB\r\nSIM: 1 Nano SIM & 1 eSIMHỗ trợ 5G\r\nPin, Sạc: 3240 mAh20 W', 0, 0.0),
(52, 'iPhone 12 Pro Max', 18990000.00, 86, 'thumb-iphone12prm-2.jpg,iphone12prm-1.jpg,iphone12prm-3.jpg,iphone12prm-4.jpg,iphone12prm-5.jpg', 5.00, 0, 6, '2023-03-13 16:19:19', '2023-03-14 18:40:31', 'Điện thoại iPhone 12 Pro Max: Nâng tầm đẳng cấp sử dụng\r\nCứ mỗi năm, đến dạo cuối tháng 8 và gần đầu tháng 9 thì mọi thông tin sôi sục mới về chiếc iPhone mới lại xuất hiện. Apple năm nay lại ra thêm một chiếc iPhone mới với tên gọi mới là iPhone 12 Pro Max, đây là một dòng điện thoại mới và mạnh mẽ nhất của nhà Apple năm nay. Mời bạn tham khảo thêm một số mô tả sản phẩm bên dưới để bạn có thể ra quyết định mua sắm.\r\nMàn hình 6.7 inches Super Retina XDR\r\nRAM 6GB đa nhiệm thoải mái, bộ nhớ trong dung lượng lớn\r\nCon chip Apple A14 SoC 5nm, RAM 6GB mạnh mẽ\r\nCụm 3 camera sau với độ phân giải 12MP  \r\nCamera trước 12MP hỗ trợ mở FaceiD cùng công nghệ chống nước IP68\r\nViên pin liền cho thời lượng sử dụng lên đến cả ngày cùng công nghệ sạc nhanh ', 2, 6, 'Kích thước màn hình 6.7 inches\r\nCông nghệ màn hình OLED\r\nCamera sau Camera chính: 12 MP, f/1.6, 26mm, 1.4µm, dual pixel PDAF, OIS\r\nCamera tele: 12 MP, f/2.0, 52mm, 1/3.4\", 1.0µm, PDAF, OIS, 2x optical zoom\r\nCamera góc siêu rộng: 12 MP, f/2.4, 120˚, 13mm, 1/3.6\"\r\nCảm biến: TOF 3D LiDAR scanner\r\nCamera trước 12 MP, f/2.2, 23mm (wide), 1/3.6\"\r\nSL 3D, (depth/biometrics sensor)\r\nChipset Apple A14 Bionic (5 nm)\r\nCông nghệ màn hình Super Retina XDR OLED, HDR10, Dolby Vision, Wide color gamut, True-tone\r\nDung lượng RAM 6 GB\r\nBộ nhớ trong 128 GB\r\nPin Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0\r\nThẻ SIM 2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)', 0, 0.0),
(53, 'iPhone 12 Pro ', 14990000.00, 97, 'thumb-iphone12pro-1.jpg,iphone12pro-2.jpg,iphone12pro-3.jpg,iphone12pro-4.jpg,iphone12pro-5.jpg', 5.00, 0, 4, '2023-03-13 16:19:19', '2023-03-14 18:40:31', '\"Điện thoại iPhone 12 Pro chính hãng (vn/a) – Dung lượng bộ nhớ trong lớn\r\nMẫu iPhone 2020 mới nhất của Apple được thiết kế khung viền vuông sang trọng được nhiều người dùng yêu thích. Trong đó, phiên bản iPhone 12 Pro chính hãng VNA hứa hẹn là một trong những sự lựa chọn lý tưởng.\r\nThiết kế sang trọng, phiên bản VNA chính hãng Việt Nam\"', 2, 6, '\"Công nghệ màn hình Super Retina XDR OLED, HDR10, Dolby Vision, Wide color gamut, True-tone\r\nKích thước màn hình 6.1 inches\r\nCông nghệ màn hình OLED\r\nCamera sau 12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS\r\n12 MP, f/2.0, 52mm (telephoto), 1/3.4\"\", 1.0µm, PDAF, OIS, 2x optical zoom\r\n12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6\"\"\r\nTOF 3D LiDAR scanner (depth)\r\nCamera trước 12 MP, f/2.2, 23mm (wide), 1/3.6\"\"\r\nSL 3D, (depth/biometrics sensor)\r\nChipset Apple A14 Bionic (5 nm)\r\nDung lượng RAM 6 GB\r\nBộ nhớ trong 256 GB\r\nPin Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0\r\nThẻ SIM 2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)\"', 0, 0.0),
(54, 'iPhone 12 Mini', 10990000.00, 93, 'iphone12mini5.jpg,thumb-iphone12mini1.jpg,iphone12mini2.jpg,iphone12mini3.jpg,iphone12mini4.jpg', 5.00, 0, 5, '2023-03-13 16:19:19', '2023-03-14 18:40:31', '\"Đánh giá iPhone 12 Mini - Kích thước nhỏ gọn, hiệu năng đỉnh cao\r\niPhone 12 series hiện nay đang là thế hệ smartphone hiện đại nhất của Apple, vẻ đẹp từ thiết kế, và sức hấp dẫn của các tính năng hiện đại mà dòng máy này sở hữu khiến người dùng công nghệ toàn cầu ‘đứng ngồi không yên”. iPhone 12 Mini tuy là phiên bản thấp nhất, nhưng chiếc smartphone này vẫn sở hữu những ưu điểm vượt trội về sự tiện lợi, linh động khi sử dụng và tính năng sạc nhanh cùng camera chất lượng cao.\r\nViền máy vát phẳng cùng màn hình tai thỏ 5.4 inch\r\nCụm camera 12MP cho khả năng chụp hình sắc nét\r\nTrang bị chip Apple A14 và RAM 4GB, bộ nhớ trong 64GB\r\nPin lithium-ion hỗ trợ sạc nhanh 20W, kể cả sạc không dây\"', 2, 6, '\"Công nghệ màn hình Super Retina XDR OLED, HDR10, Dolby Vision, Wide color gamut, True-tone\r\nKích thước màn hình 5.4 inches\r\nCông nghệ màn hình OLED\r\nCamera sau 12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS\r\n12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6\"\"\r\nCamera trước 12 MP, f/2.2, 23mm (wide), 1/3.6\"\"\r\nSL 3D, (depth/biometrics sensor)\r\nChipset Apple A14 Bionic (5 nm)\r\nDung lượng RAM 4 GB\r\nBộ nhớ trong 64 GB\r\nPin Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0\r\nThẻ SIM 2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)\r\nĐộ phân giải màn hình 1080 x 2340 pixels (FullHD+)\"', 0, 0.0),
(55, 'iPhone 12', 12990000.00, 100, 'thumb-iphone12-2.jpg,iphone12-1.jpg,iphone12-3.jpg,iphone12-4.jpg,iphone12-5.jpg', 5.00, 0, 1, '2023-03-13 16:19:19', '2023-03-14 18:40:31', '\"Apple iPhone 12 128GB chính hãng (VN/A) phiên bản bộ nhớ 128GB lưu trữ thoải mái\r\niPhone 12 hiện nay là cái tên “sốt xình xịch” bởi đây là một trong 4 siêu phẩm vừa được ra mắt của Apple với những đột phá về cả thiết kế lẫn cấu hình. Phiên bản Apple iPhone 12 128GB chính là một trong những chiếc iPhone được săn đón nhất bởi dung lượng bộ nhớ khủng, cho phép bạn thoải mái với vô vàn ứng dụng.\r\nDung lượng bộ nhớ trong lên đến 128GB và chip Apple A14 độc quyền\r\nThiết kế độc đáo với viền vát phẳng mạnh mẽ và hỗ trợ sạc nhanh 20W\"', 2, 6, '\"Kích thước màn hình 6.1 inches\r\nCông nghệ màn hình OLED\r\nCamera sau 12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS 12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6\"\"\r\nCamera trước 12 MP, f/2.2, 23mm (wide), 1/3.6\"\" SL 3D, (depth/biometrics sensor)\r\nChipset Apple A14 Bionic (5 nm)\r\nCông nghệ màn hình Super Retina XDR OLED, HDR10, Dolby Vision, Wide color gamut, True-tone\r\nDung lượng RAM 4 GB\r\nBộ nhớ trong 128 GB\r\nPin Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0\r\nThẻ SIM 2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)\r\nĐộ phân giải màn hình 1170 x 2532 pixels\"', 0, 0.0),
(56, 'iPhone 11 Pro Max', 11990000.00, 99, 'iphone11prm4.png,iphone11prm3.jpg,iphone11prm2.png,thumb-iphone11prm1.png', 5.00, 0, 0, '2023-03-13 16:35:00', '2023-03-14 18:40:31', '\"Điện thoại iPhone 11 Pro Max: Nâng tầm đẳng cấp sử dụng\r\nCứ mỗi năm, đến dạo cuối tháng 8 và gần đầu tháng 9 thì mọi thông tin sôi sục mới về chiếc iPhone mới lại xuất hiện. Apple năm nay lại ra thêm một chiếc iPhone mới với tên gọi mới là iPhone 11 Pro Max, đây là một dòng điện thoại mới và mạnh mẽ nhất của nhà Apple năm nay. Mời bạn tham khảo thêm một số mô tả sản phẩm bên dưới để bạn có thể ra quyết định mua sắm.\r\nMàn hình 6.5 inches Super Retina XDR\r\nRAM 6GB đa nhiệm thoải mái, bộ nhớ trong dung lượng lớn\r\nCon chip Apple A12 SoC 5nm, RAM 6GB mạnh mẽ\r\nCụm 3 camera sau với độ phân giải 12MP  \r\nCamera trước 12MP hỗ trợ mở FaceiD cùng công nghệ chống nước IP68\r\nViên pin liền cho thời lượng sử dụng lên đến cả ngày cùng công nghệ sạc nhanh \"', 2, 7, '\"Công nghệ màn hình Super Retina XDR\r\nKích thước màn hình 6.5 inches\r\nCamera sau\r\n3 Camera 12MP:\r\n- Camera tele: ƒ/2.0 aperture\r\n- Camera góc rộng: ƒ/1.8 aperture\r\n- Camera siêu rộng: ƒ/2.4 aperture\r\nCamera trước 12 MP ƒ/2.2 aperture\r\nChipset A13 Bionic\r\nDung lượng RAM 4 GB\r\nBộ nhớ trong 256 GB\r\nPin 3969 mAh\r\nThẻ SIM Nano-SIM + eSIM\r\nHệ điều hành iOS 13 hoặc cao hơn (Tùy vào phiên bản phát hành)\r\nĐộ phân giải màn hình 2688 x 1242 pixels\"', 0, 0.0),
(57, 'iPhone 11 Pro ', 9990000.00, 99, 'iphone11pro4.png,thumb-iphone11pro1.png,iphone11pro2.png,iphone11pro3.png', 5.00, 0, 0, '2023-03-13 16:35:00', '2023-03-14 18:40:31', '\"Điện thoại iPhone 11 Pro chính hãng (vn/a) – Dung lượng bộ nhớ trong lớn\r\nMẫu iPhone 2019 mới nhất của Apple được thiết kế khung viền vuông sang trọng được nhiều người dùng yêu thích. Trong đó, phiên bản iPhone 11 Pro chính hãng VNA hứa hẹn là một trong những sự lựa chọn lý tưởng.\r\nThiết kế sang trọng, phiên bản VNA chính hãng Việt Nam\"', 2, 7, '\"Kích thước màn hình 5.8 inches\r\nCamera sau 3 Camera 12MP:\r\n- Camera tele: ƒ/2.0 aperture\r\n- Camera góc rộng: ƒ/1.8 aperture\r\n- Camera siêu rộng: ƒ/2.4 aperture\r\nCamera trước 12 MP ƒ/2.2 aperture\r\nChipset A13 Bionic\r\nCông nghệ màn hình Super Retina XDR\r\nDung lượng RAM 4 GB\r\nBộ nhớ trong 64 GB\r\nPin 3046 mAh\r\nThẻ SIM Nano-SIM + eSIM\r\nHệ điều hành iOS 13 hoặc cao hơn (Tùy vào phiên bản phát hành)\"', 0, 0.0),
(58, 'iPhone 11', 7490000.00, 100, 'thumb-iphone11-1.jpg,iphone11-2.jpg,iphone11-3.jpg,iphone11-4.jpg,iphone11-5.jpg', 5.00, 0, 0, '2023-03-13 16:35:00', '2023-03-14 18:40:31', '\"Apple iPhone 11 128GB chính hãng (VN/A) phiên bản bộ nhớ 128GB lưu trữ thoải mái\r\niPhone 11 hiện nay là cái tên “sốt xình xịch” bởi đây là một trong 4 siêu phẩm vừa được ra mắt của Apple với những đột phá về cả thiết kế lẫn cấu hình. Phiên bản Apple iPhone 11 128GB chính là một trong những chiếc iPhone được săn đón nhất bởi dung lượng bộ nhớ khủng, cho phép bạn thoải mái với vô vàn ứng dụng.\r\nDung lượng bộ nhớ trong lên đến 128GB và chip Apple A13 độc quyền\r\nThiết kế độc đáo với viền vát phẳng mạnh mẽ và hỗ trợ sạc nhanh 20W\"', 2, 7, '\"Kích thước màn hình 6.1 inches\r\nCông nghệ màn hình IPS LCD\r\nCamera sau Camera kép 12MP:\r\n- Camera góc rộng: ƒ/1.8 aperture\r\n- Camera siêu rộng: ƒ/2.4 aperture\r\nCamera trước 12 MP, ƒ/2.2 aperture\r\nChipset A13 Bionic\r\nCông nghệ màn hình IPS LCD\r\nDung lượng RAM 4 GB\r\nBộ nhớ trong 128 GB\r\nPin 3110 mAh\r\nThẻ SIM Nano-SIM + eSIM\r\nHệ điều hành iOS 13 hoặc cao hơn (Tùy vào phiên bản phát hành)\"', 0, 0.0),
(59, 'iPhone XS Max', 7990000.00, 100, 'iphonexsm4.jpg,iphonexsm1.jpg,iphonexsm2.jpg,thumb-iphonexsm.jpg,iphonexsm3.jpg', 5.00, 0, 1, '2023-03-13 16:35:00', '2023-03-14 18:40:31', '\"Apple iPhone XS Max\r\nSau kỷ niệm 10 năm bằng cách ra mắt iPhone X, nhiều người tự hỏi sau đó, Apple sẽ làm gì. Apple đã giải đáp thắc mắc này bằng cách ra mắt ba sản phẩm smartphone cao cấp mới của mình. Trong đó, Apple iPhone XS Max  xứng tầm là chiếc smartphone cao cấp nhất hiện nay. Bạn có thể tham khảo thêm iPhone XS Max 512GB chính hãng VN/A để được bảo hành 12 tháng tại Việt Nam.\r\nThiết kế Apple iPhone XS Max sang trọng, đẳng cấp\r\nMàn hình Apple iPhone XS Max đỉnh cao về màu sắc\r\nHiệu năng Apple iPhone XS Max hàng đầu\"', 2, 8, '\"Công nghệ màn hình Super Retina OLED\r\nKích thước màn hình 6.5 inches\r\nCamera sau 12 MP\r\nCamera trước 7 MP\r\nChipset Apple A12 Bionic 6 nhân\r\nBộ nhớ trong 512 GB\r\nPin Li-ion\r\nThẻ SIM Nano-SIM\r\nHệ điều hành 12\r\nĐộ phân giải màn hình 1242 x 2688 pixel\"', 0, 0.0),
(67, 'Samsung Galaxy A04s', 3590000.00, 0, 'a04-1.jpg,a04-2.png,a04-3.png,a04-4.png,thumb-anhchinh1.jpg', 5.00, 0, 2, '2023-03-17 13:15:06', '2023-03-17 13:59:48', 'Samsung A04s (4GB/64GB) là điện thoại mới phân khúc giá rẻ, sở hữu chip 8 nhân Exynos 850, khả năng đa nhiệm, lưu trữ ổn định, chụp ảnh đẹp. Thêm vào đó, màn hình LCD 6.5 inch có độ phân giải HD+ và tần số quét 90Hz cho trải nghiệm hình ảnh sắc nét, rõ ràng.\r\nNgoại hình Samsung Galaxy A04s năng động, linh hoạt cùng màn hình 6.5 inch HD+\r\nHệ thống camera Samsung A04s ba ống kính chụp ảnh nổi bật\r\n', 3, 11, '\"- Kích thước màn hình: 6.5 inches\r\n- Công nghệ màn hình: IPS LCD\r\n- Camera sau:\r\n+ Camera chính: 50MP, f/1.8\r\n+ Camera Macro: 2MP, f/2.8\r\n+ Camera góc sâu: 2MP, f/2.4\r\n- Camera trước: 5 MP, f/2.2\r\n- Chipset: Exynos 850 8 nhân\r\n- RAM: 4GB\r\n- ROM: 64GB\r\n- Pin: 5,000mAh\r\n- Hệ điều hành: Android 12 One UI\r\n- Độ phân giải màn hình: 1366 x 768 pixels (HD+)\r\n- Tính năng màn hình: Tần số quét 90 Hz, Kính cường lực Corning Gorilla Glass 3\"', 0, 0.0),
(68, 'Samsung Galaxy A13 (4G 128GB) ', 3490000.00, 100, 'a13-1.jpg,a13-2.png,a13-3.png,a13-4.png,thumb-anhchinh2.jpg', 5.00, 0, 1, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Thảo sức tận hưởng thế giới giải trí sống động - Màn hình TFT LCD, 6.6 inch\r\nHiệu năng ổn định, ấn tượng - Chip Exynos 850 mạnh mẽ, xử lí tốt mọi tác vụ\r\nCamera nâng cấp với nhiều tính năng độc đáo - Cụm 4 camera 50MP, 5MP, 2MP và 2MP\r\nThoải mái trải nghiệm với pin dung lượng 5000 mAh, sạc nhanh 15W', 3, 11, '\"- Kích thước màn hình: 6.6 inches\r\n- Công nghệ màn hình: IPS LCD\r\n- Camera sau: 50MP + 5MP + 2MP + 2MP\r\n- Camera trước: 8 MP\r\n- Chipset: Exynos 850 8 nhân\r\n- RAM: 4GB\r\n- ROM: 128GB\r\n- Pin: Li-po 5,000mAh\r\n- Hệ điều hành: Android 12\r\n- Độ phân giải màn hình: 1080 x 2408 pixels\r\n\"', 0, 0.0);
INSERT INTO `tbl_sanpham` (`masanpham`, `tensp`, `don_gia`, `ton_kho`, `images`, `giam_gia`, `dac_biet`, `so_luot_xem`, `ngay_nhap`, `date_modified`, `mo_ta`, `ma_danhmuc`, `id_dmphu`, `information`, `promote`, `danhgia`) VALUES
(69, 'Samsung Galaxy A14 ', 4990000.00, 100, 'a14-1.png,a14-2.png,a14-3.png,a14-4.png,thumb-anhchinh3.png', 5.00, 0, 2, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Giải trí cực đã - Màn hình 6.6\"\" FullHD, tần số quét 90Hz hệ thống loa vòm Dolby Atmos\r\nKết nối nhanh, mượt mà - Dòng sản phẩm hiếm có hỗ trợ 5G trong tầm giá, đi kèm chip Dimensity 700\r\nCamera chụp ảnh đã chế độ - Camera 50MP, chụp toàn cảnh, chụp cận cảnh, chụp xoá phông\r\nSử dụng đến 2.5 ngày - Với Pin 5000mAh, sạc nhanh 15W\r\n', 3, 11, '\"- Kích thước màn hình: 6.5 inches\r\n- Công nghệ màn hình: IPS LCD\r\n- Camera sau:\r\n+ Camera góc rộng: 50MP, f/1.8, 26mm, PDAF\r\n+ Camera macro: 2MP, f/2.4\r\n+ Camera đo độ sâu: 2MP, f/2.4\r\n- Camera trước: 13MP\r\n- Chipset: MediaTek Dimensity 700\r\n- RAM: 4GB\r\n- ROM: 128GB\r\n- Pin: 5,000mAh\r\n- Hệ điều hành: Android 13\r\n- Độ phân giải màn hình: 720 x 1600 pixel\r\n- Tính năng màn hình: Tần số quét 90 Hz\"', 0, 0.0),
(70, 'Samsung Galaxy A23 (4GB 128GB)', 7290000.00, 97, 'a23-1.jpg,a23-2.png,a23-3.png,a23-4.png,thumb-anhchinh4.jpg', 5.00, 0, 1, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Samsung Galaxy A23 gây ấn tượng ban đầu với người dùng nhờ sở hữu ngoại hình đơn giản nhưng vẫn bắt mắt với đa dạng các màu sắc khác nhau. Chiếc smartphone này luôn nằm trong danh sách các dòng điện thoại dưới 5 triệu đáng mua nhất nhờ sở hữu hiệu năng mạnh mẽ, đa dạng các chế độ chụp ảnh, thời lượng sử dụng lâu dài,...\r\n\r\nNăm 2023, Samsung cho ra mắt điện thoại Samsung Galaxy A24 mà quý khách có thể quan tâm!', 3, 11, '\"- Kích thước màn hình: 6.6 inches\r\n- Công nghệ màn hình: TFT LCD\r\n- Camera sau: 50MP + 5MP + 2MP + 2MP\r\n- Camera trước: 8 MP\r\n- Chipset: Snapdragon 680 (SM6225)\r\n- RAM: 4GB\r\n- ROM: 128GB\r\n- Pin: 5,000mAh\r\n- Hệ điều hành: Android 11\r\n- Tính năng màn hình: 1080 pixels FHD+, 90 Hz, Kính cường lực Corning Gorilla Glass 5\"', 0, 0.0),
(71, 'Samsung Galaxy A33 (5G)', 7290000.00, 100, 'a33-1.jpg,a33-2.png,a33-3.png,a33-4.png,thumb-anhchinh5.jpg', 5.00, 0, 0, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Ngay sau khi ra mắt không lâu, điện thoại Galaxy A33 chính hãng đã mặt tại thị trường Việt Nam với giá bán niêm yết là 8.49 triệu đồng. Với mức giá này, sản phẩm sẽ cạnh tranh với các đối thủ như OPPO Reno6 Z 5G, Xiaomi Redmi Note 11 Pro Plus 5G...\r\n\r\nBạn cũng có thể truy cập ngay trang web hoặc đến các cửa hàng của CellphoneS để trải nghiệm. Tại đây, mức giá của Samsung A33 đang vô cùng hấp dẫn cùng nhiều chương trình ưu đãi dành do khách hàng.\r\n\r\nNăm 2023, Samsung ra mắt Samsung Galaxy A34 với nhiều cải tiến như màn hình Super AMOLED 6.6 inch, tần số quét 120Hz, độ sáng lên đến 1.000 nits, pin 5.000mAh với camera sắc nét tích hợp công nghệ chống rung OIS. Mời bạn tham khảo thêm!', 3, 11, '\"- Kích thước màn hình: 6.4 inches\r\n- Công nghệ màn hình: Super AMOLED\r\n- Camera sau:\r\n+ Camera chính: 48 MP, F1.8\r\n+ Camera góc siêu rộng: 8 MP, F2.2\r\n+ Camera macro: 5 MP, F2.4\r\n+ Camera chân dung: 2.0 MP, F2.4\r\n- Camera trước: 13 MP, f/2.2\r\n- Chipset: Vi xử lý 8 nhân Exynos 1280\r\n- RAM: 6GB\r\n- ROM: 128GB\r\n- Pin: 5,000mAh\r\n- Hệ điều hành: Android 12\r\n- Tính năng màn hình: Tần số quét 90 Hz, Kính cường lực Corning Gorilla Glass 5\"', 0, 0.0),
(72, 'Samsung Galaxy A52', 9290000.00, 100, 'a52-1.jpg,a52-2.jpg,a52-3.jpg,a52-4.jpg,thumb-anhchinh6.jpg', 5.00, 0, 0, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Điện thoại Samsung Galaxy A52 – Camera sau nâng cấp, cấu hình mạnh mẽ\r\nSau thành công của Samsung Galaxy A51 với mức doanh số khá tốt thì trong năm 2020, Samsung lại tiếp tục cho ra mắt mẫu smartphone Galaxy A52 với những cải tiến về hệ thống camera cũng như được trang bị cấu hình mạnh mẽ cho trải nghiệm tuyệt vời.\r\n\r\nNgoài ra, bạn cũng có thể tham khảo thêm điện thoại Samsung Galaxy A52s với nhiều nâng cấp về cấu hình và camera.\r\n\r\nThiết kế sang trọng, tinh tế với các màu sắc thời trang', 3, 11, '\"- Kích thước màn hình: 6.5 inches\r\n- Công nghệ màn hình: Super AMOLED\r\n- Camera sau:\r\n+ Camera góc rộng: 64 MP, f/1.8, 26mm, PDAF, OIS\r\n+ Camera góc siêu rộng: 12 MP, f/2.2, 123˚\r\n+Camera cận cảnh: 5 MP, f/2.4\r\n+ Cảm biến chiều sâu: 5 MP, f/2.2\r\n- Camera trước: 32 MP, f/2.2, 26mm, 1/2.8\"\", 0.8µm\r\n- Chipset: Snapdragon 720G (8 nm)\r\n- RAM: 8GB\r\n- ROM: 128GB\r\n- Pin: Li-Po 4500 mAh\r\n- Cảm biến: Cảm biến vân tay, cảm biến tiệm cận, gia tốc kế, la bàn, con quay hồi chuyển\r\n- Tính năng màn hình: Tần số quét 90Hz, độ sáng tối đa 800 nits\"', 0, 0.0),
(73, 'Samsung Galaxy A73 (5G)', 10290000.00, 98, 'a73-1.jpg,a73-2.jpg,a73-3.png,a73-4.png,thumb-anhchinh7.jpg', 5.00, 0, 0, '2023-03-17 13:26:50', '2023-03-17 13:59:48', '5G thần tốc: mang cho bạn trải nghiệm đỉnh cao với tốc độ kết nối mạnh mẽ. Bạn có thể thoải mái tận hưởng và chia sẻ tức thì mọi nội dung giải trí cũng như kết nối với mọi người một cách nhanh chóng.\r\nKhả năng đa nhiệm được tối ưu: Được trang bị Snapdragon® 778G 5G, Galaxy A73 5G thay đổi hoàn toàn nâng tầm thói quen đa nhiệm với khả năng chơi game chuyên nghiệp. AI được tăng tốc để có hiệu suất thông minh hơn và trải nghiệm chụp ảnh cao cấp. Ngoài ra, khi bạn cần nhiều bộ nhớ hơn, RAM Plus  của A73 ngay lập tức cung cấp thêm RAM ảo.\r\nThoải mái lưu giữ mọi khoảnh khắc: Bạn có thể lưu giữ những khoảnh khắc quý giá của mình nhiều hơn nhờ bộ nhớ trong 128GB/256GB.\r\nMàn hình sắc nét: Công nghệ FHD+ Super AMOLED Plus với Màn hình Infinity-O 6,7\" mở rộng, các khung hình được chụp bằng máy ảnh Góc rộng 108MP giữ trọn vẹn các chi tiết sống động như thật. Người dùng có thể tận hưởng khả năng hiển thị ngoài trời sống động lên đến 800 nits¹ hoặc bảo vệ mắt tối ưu với chức năng giảm ánh sáng xanh Eye Comfort Shield². Bạn có thể thoả thích xem mọi nội dung nhờ tần số quét 120Hz công nghệ Super AMOLED Plus để tận hưởng những khung hình mượt mà, không mờ nhoè, siêu chi tiết và độ tương phản sắc nét.', 3, 11, '\"- Kích thước màn hình: 6.7 inches\r\n- Công nghệ màn hình: Super AMOLED\r\n- Camera sau:\r\n+ Camera chính: 108 MP, f/1.8, PDAF, OIS\r\n+ Camera gó siêu rộng: 12 MP, f/2.2\r\n+ Camera macro: 5 MP, f/2.4\r\n+ Camera chân dung: 5 MP, f/2.4\r\n- Camera trước: 32 MP, f/2.2\r\n- Chipset: Snapdragon 778G 5G 8 nhân\r\n- RAM: 8GB\r\n- ROM: 256GB\r\n- Pin: 5,000mAh\r\n- Hệ điều hành: Android 12 One UI 4.1\r\n- Độ phân giải màn hình: 1080 x 2400 pixels (FullHD+)\r\n- Tính năng màn hình: Tần số quét 120 Hz, Kính cường lực Corning Gorilla Glass 5\"', 0, 0.0),
(74, 'Samsung Galaxy M32', 4550000.00, 100, 'm32-1.jpg,m32-2.png,m32-3.png,m32-4.png,thumb-anhchinh8.jpg', 5.00, 0, 0, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Điện thoại Samsung M32 là mẫu điện thoại Samsung thuộc phân khúc giá rẻ mới được ra mắt trên thị trường. Điện thoại Samsung M32 là sản phẩm thuộc series Samsung M được kế thừa nhiều ưu điểm từ dòng Samsung A. Điện thoại được trang bị màn hình 6,4 inch Infinity-U với độ phân giải  FHD+ mang lại khả năng hiển thị ấn tượng. Bên cạnh đó là một hiệu năng ổn định với chip MediaTek Helio G80, bộ nhớ RAM 8GB, dung lượng pin 5000 mAh.\r\n\r\nĐánh giá điện thoại Samsung Galaxy M32 – điện thoại Samsung giá rẻ\r\nMới đây Samsung tiếp tục cho ra mắt mẫu điện thoại giá rẻ Samsung M32. Đây là điện thoại thuộc dòng điện thoại Galaxy M ở phân khúc giá rẻ nhưng được trang bị cấu hình tương đối ổn định. Ngoài ra, bạn cũng có thể tham khảo thêm điện thoại Samsung Galaxy M32s với cấu hình được nâng cấp.', 3, 12, '\"- Kích thước màn hình: 6.4 inches\r\n- Công nghệ màn hình: Super AMOLED\r\n- Camera sau:\r\n+ Camera chính: 64 MP, f/1.8\r\n+ Camera góc siêu rộng: 8 MP, f/2.2\r\n+ Camera cận cảnh: 2 MP, f/2.4\r\n+ Cảm biến độ sâu: 2 MP, f/2.4\r\n- Camera trước: 20 MP, f/2.2\r\n- Chipset: Mediatek Helio G80 (12 nm)\r\n- RAM: 8GB\r\n- ROM: 128GB\r\n- Pin: 5,000mAh\r\n- Hệ điều hành: Android 11, One UI 3.1\r\n- Độ phân giải màn hình: 1080 x 2400 pixels (FullHD+)\r\n- Tính năng màn hình: Độ sáng 800 nits\"', 0, 0.0),
(75, 'Samsung Galaxy Note 20 Ultra 5G', 32990000.00, 100, 'n20u-1.jpg,n20u-2.jpg,n20u-3.jpg,n20u-4.jpg,thumb-anhchinh9.jpg', 5.00, 0, 0, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Điện thoại Samsung Note 20 Ultra 5G - Sang trọng, hiệu năng vượt trội\r\nBên cạnh biên bản Galaxy Note 20 thường, Samsung còn cho ra mắt Note 20 Ultra 5G cho khả năng kết nối dữ liệu cao cùng thiết kế nguyên khối sang trọng, bắt mắt. Đây sẽ là sự lựa chọn hoàn hảo dành cho bạn để sử dụng mà không bị lỗi thời sau thời gian dài ra mắt.\r\n\r\nNgoài ra, bạn có thể tham khảo điện thoại màn hình gập Samsung Fold 3 nếu bạn cần sự khác biệt và khẳng định đẳng cấp.\r\n\r\nThiết kế khung nhôm nguyên khối, mặt sau kính cường lực sang trọng\r\nLà một sản phẩm có kích thước màn hình lớn vì vậy Samsung đã trang bị cho Galaxy Note 20 Ultra 5G  với công nghệ kết nối dữ liệu mạnh mẽ cùng thiết kế nguyên khối. Giúp các linh kiện bên trong điện thoại được cố định chắc chắn đảm bảo mọi thứ bên trong luôn được an toàn. Không những vậy khung nhôm tạo trên những đường viền cực kỳ sang trọng và bắt mắt khi nhìn vào.', 3, 12, '\"- Kích thước màn hình: 6.9 inches\r\n- Công nghệ màn hình: Dynamic AMOLED\r\n- Camera sau:\r\n+ 108 MP, f/1.8, 26mm (wide), 1/1.33\"\", 0.8µm, PDAF, Laser AF, OIS\r\n+ 12 MP, f/3.0, 103mm (periscope telephoto), 1.0µm, PDAF, OIS, 5x optical zoom, 50x hybrid zoom\r\n+ 12 MP, f/2.2, 13mm (ultrawide), 1/2.55\"\", 1.4µm\r\n- Camera trước:10 MP, f/2.2, 26mm (wide), 1/3.2\"\", 1.22µm, Dual Pixel PDAF\r\n- Chipset: Exynos 990 (7 nm+)\r\n- Công nghệ màn hình: Dynamic AMOLED 2X capacitive touchscreen\r\n- RAM: 12 GB\r\n- ROM: 256 GB\r\n- Pin: Non-removable Li-Ion 4500 mAh battery, Fast charging 25W\r\n- Hệ điều hành: Android 10, One UI 2.1\r\n- Độ phân giải màn hình: 1440 x 3088 pixels (QHD+)\r\n- Tính năng màn hình:120Hz, HDR10+, Corning Gorilla Glass Victus\r\n- Cảm biến: Cảm biến vân tay siêu âm, cảm biến gia tốc\"', 0, 0.0),
(76, 'Samsung Galaxy S21 FE 8GB 128GB ', 12490000.00, 99, 's21fe-1.png,s21fe-2.png,s21fe-3.png,s21fe-4.png,thumb-anhchinh10.png', 5.00, 0, 0, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Samsung Galaxy S21 FE (8GB - 128GB) được cung cấp sức mạnh bởi con chip xử lý Exynos 2100 \"cây nhà lá vườn\" kết hợp với 8GB RAM mang đến hiệu suất hoạt động mạnh mẽ cùng bộ nhớ trong 128GB giúp người dùng có thể thoải mái lưu trữ hình ảnh, video dữ liệu.', 3, 10, '\"Kích thước màn hình\r\n\r\n6.4 inches\r\nCông nghệ màn hình\r\n\r\nSuper AMOLED\r\nCamera sau\r\n\r\nCamera góc rộng: 12 MP, f/1.8, PDAF, OIS\r\nCamera tele: 8 MP, f/2.4, 3x optical zoom\r\nCamera góc siêu rộng: 12 MP, f/2.2\r\nCamera trước\r\n\r\n32 MP, f/2.2\r\nChipset\r\n\r\nExynos 2100 (5nm)\r\nDung lượng RAM\r\n\r\n8 GB\r\nBộ nhớ trong\r\n\r\n128 GB\r\nPin\r\n\r\n4500mAh\r\nThẻ SIM\r\n\r\n2 SIM (Nano-SIM)\r\nĐộ phân giải màn hình\r\n\r\n1080 x 2400 pixels (FullHD+)\r\nTính năng màn hình\r\n\r\nTrang bị Spen Pro\"', 0, 0.0),
(77, 'Samsung Galaxy S22 (8GB - 256GB)', 16390000.00, 100, 's22-1.jpg,s22-2.png,s22-3.jpg,s22-4.png,thumb-anhchinh11.jpg', 5.00, 0, 1, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Camera mắt thần bóng đêm Nightography - Ghi lại khoảnh khắc đêm diệu kì\r\nMãn nhãn từng khoảnh khắc - Màn hình 6.1\", Dynamic AMOLED 2X, 120Hz\r\nBứt phá hiệu năng - Snapdragon 8 Gen 1 (4 nm)\r\nThỏa sức trải nghiệm chỉ với một lần sạc - Viên pin 3700 mAh, sạc nhanh 25W, sạc không dây', 3, 10, '\"Kích thước màn hình 6.1 inches\r\nCông nghệ màn hình Dynamic AMOLED 2X \r\nCamera sau \r\nCamera chính: 50MP, f/1.8 \r\nCamera góc siêu rộng: 12MP, f/2.2 \r\nCamera tele: 10MP, f/2.4 \r\nCamera trước 10MP \r\nChipset Chip Snapdragon 8 Gen 1\r\nRAM 8 GB \r\nBộ nhớ trong 256 GB \r\nPin 3700 mAh \r\nThẻ SIM 2 SIM (nano‑SIM và eSIM) \r\nHệ điều hành Android 12, One UI 4.1 \r\nĐộ phân giải màn hình 1080 x 2340 pixels (FullHD+) \r\nTính năng màn hình Corning Gorilla Glass Victus+, HDR10+, 1300 nits\"', 0, 0.0),
(78, 'Samsung Galaxy S23 Plus 8GB 256GB', 24990000.00, 100, 's23p-1.jpg,s23p-2.jpg,s23p-3.jpg,s23p-4.jpg,thumb-anhchinh12.jpg', 5.00, 0, 0, '2023-03-17 07:15:06', '2023-03-17 13:59:48', 'Samsung Galaxy S23 Plus trang bị màn hình 6.6 inch, công nghệ màn hình sắc nét, với cụm camera sau ấn tượng với camera góc siêu rộng 12 MP, camera góc rộng 50MP, ống kính tele 10MP . Bên cạnh đó, với con chipset mạnh mẽ Snapdragon 8 Gen 2, RAM 8GB và phiên bản bộ nhớ trong 256GB/512GB ổn định khi dùng trong thời gian dài. Người dùng sẽ có những khoảnh khắc bên điện thoại cả ngày, chiến game, giải trí với dung lượng pin 4700mAh.\r\n\r\nSo sánh Samsung Galaxy S23 Plus và Samsung Galaxy S22 Plus\r\nSo với Samsung S22 Plus, sản phẩm mới đến từ nhà Samsung đã không làm các tín đồ công nghệ thất vọng bởi cải tiến mới về mặt hiệu năng, dung lượng pin, dung lượng bộ nhớ và tính năng chụp đêm ấn tượng. Xem ngay thông tin sự thay đổi qua bảng sau đây!', 3, 10, '\"Kích thước màn hình\r\n\r\n6.6 inches\r\nCông nghệ màn hình\r\n\r\nDynamic AMOLED 2X\r\nCamera sau\r\n\r\nCamera chính góc rộng: 50 MP, f/1.8, Dual Pixel PDAF, OIS\r\nCamera tele: 10 MP, f/2, 3x optical zoom\r\nCamera góc siêu rộng:12 MP, f/2.2\r\nCamera trước\r\n\r\n12MP, f/2.2\r\nChipset\r\n\r\nSnapdragon 8 Gen 2\r\nDung lượng RAM\r\n\r\n8 GB\r\nBộ nhớ trong\r\n\r\n256 GB\r\nPin\r\n\r\n4700 mAh\r\nThẻ SIM\r\n\r\n2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành\r\n\r\nAndroid\r\nĐộ phân giải màn hình\r\n\r\n1080 x 2340 pixels (FullHD+)\r\nTính năng màn hình\r\n\r\nTần số quét 120Hz, HDR10+, Kính cường lực Corning® Gorilla® Glass Victus® 2\r\nTương thích\r\n\r\nKhông hỗ trợ bút S-Pen\"', 0, 0.0),
(79, 'Samsung Galaxy Z Flip4 128GB ', 20990000.00, 100, 'thumb-anhchinh14.jpg,zflip4-1.jpg,zflip4-2.png,zflip4-3.png,zflip4-4.png', 5.00, 0, 1, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Tiếp tục là một mẫu smartphone màn hình gập độc đáo, đầy lôi cuốn và mới mẻ từ hãng công nghệ Hàn Quốc, dự kiến sẽ có tên là Samsung Galaxy Z Flip 4 với nhiều nâng cấp. Đây hứa hẹn sẽ là một siêu phẩm bùng nổ trong thời gian tới và thu hút được sự quan tâm của đông đảo người dùng với nhiều cải tiến từ ngoại hình, camera, bộ vi xử lý và viên pin được nâng cấp.', 3, 9, '\"Kích thước màn hình\r\n\r\n6.7 inches\r\nCông nghệ màn hình\r\n\r\nDynamic AMOLED 2X\r\nCamera sau\r\n\r\nCamera góc rộng: 12 MP, f/1.8, PDAF, OIS\r\nCamera góc siêu rộng: 12 MP, f/2.2, 123˚\r\nCamera trước\r\n\r\n10 MP, f/2.4\r\nChipset\r\n\r\nSnapdragon 8+ Gen 1 (4 nm)\r\nDung lượng RAM\r\n\r\n8 GB\r\nBộ nhớ trong\r\n\r\n128 GB\r\nPin\r\n\r\n3700 mAh\r\nThẻ SIM\r\n\r\n2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành\r\n\r\nAndroid 12, One UI 4.1.1\r\nTính năng màn hình\r\n\r\nMàn hình chính: 6.7 inches\r\nMàn hình ngoài: 2.1 inches, Super AMOLED\r\n120Hz, HDR10+, 1200 nits (peak)\"', 0, 0.0),
(80, 'Samsung Galaxy Z Fold 4', 37990000.00, 100, 'thumb-anhchinh15.jpg,zfold4-1.jpg,zfold4-2.jpg,zfold4-3.png,zfold4-4.png', 5.00, 0, 1, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Galaxy Z Fold3 vốn đã rất nổi bật thì mới đây, sự xuất hiện của điện thoại gập mới Samsung Galaxy Z Fold 4 lại càng hấp dẫn nhiều người dùng hơn khi sở hữu thiết kế gập màn hình mới cùng với những cải tiến cho trải nghiệm nhân đôi. Vậy chiếc smartphone màn hình gập cao cấp thế hệ mới có gì mới, giá bao nhiêu và có nên mua không? Cùng tìm hiểu nhé!\r\n\r\nThông tin mới nhất về điện thoại Samsung Z Fold 4\r\nTheo các nguồn thông tin gần đây, điện thoại Galaxy Z Fold 2022sẽ có những điểm mới về màu sắc, phiên bản dung lượng bộ nhớ, hiệu năng, camera cùng thiết kế mới. Dưới đây là những thông tin mới nhất về siêu phẩm màn hình gập Samsung Z Fold 4 vừa được trình làng mới đây.', 3, 9, '\"Kích thước màn hình\r\n\r\n7.6 inches\r\nCông nghệ màn hình\r\n\r\nAMOLED\r\nCamera sau\r\n\r\nCamera chính: 50MP\r\nCamera góc siêu rộng: 12MP\r\nCamera tele: 10MP (3x zoom)\r\nCamera trước\r\n\r\n10MP (bên ngoài) + 4MP (dưới màn hình)\r\nChipset\r\n\r\nSnapdragon 8 Plus Gen 1\r\nDung lượng RAM\r\n\r\n12 GB\r\nBộ nhớ trong\r\n\r\n256 GB\r\nPin\r\n\r\n4,400 mAh\r\nThẻ SIM\r\n\r\n2 Nano-SIM + eSIM\r\nHệ điều hành\r\n\r\nAndroid 12, One UI 4.1.1\r\nTính năng màn hình\r\n\r\nMàn hình chính: 7,6 inch QXGA + AMOLED, 120Hz\r\nMàn hình phụ: 6.2 inch HD + AMOLED, 120Hz\"', 0, 0.0),
(81, 'Samsung Galaxy Z Fold3 5G 256GB ', 21490000.00, 100, 'thumb-anhchinh16.jpg,zfold3-1.jpg,zfold3-2.jpg,zfold3-3.jpg,zfold3-4.jpg', 0.00, 0, 0, '2023-03-17 13:26:50', '2023-03-17 13:59:48', '', 3, 9, '\"Kích thước màn hình\r\n\r\n7.6 inches\r\nCông nghệ màn hình\r\n\r\nDynamic AMOLED\r\nCamera sau\r\n\r\nCamera góc rộng: 12 MP, f/1.8, 26mm, Dual Pixel PDAF, OIS\r\nCamera tele: 12 MP, f/2.4, 52mm, PDAF, OIS, 2x Zoom quang học\r\nCamera góc siêu rộng: 12 MP, f/2.2\r\nCamera màn hình phụ: 10MP, f/2.2\r\nCamera trước\r\n\r\nCamera ẩn dưới màn hình: 4MP, f/1.8\r\nChipset\r\n\r\nSnapdragon 888 5G (5 nm)\r\nDung lượng RAM\r\n\r\n12 GB\r\nBộ nhớ trong\r\n\r\n256 GB\r\nPin\r\n\r\nLi-Po 4400 mAh\r\nThẻ SIM\r\n\r\n2 SIM (nano‑SIM và eSIM)\r\nHệ điều hành\r\n\r\nAndroid 11\r\nTính năng màn hình\r\n\r\nMàn hình chính: 7.9\"\" 2208x1768, 374ppi, HDR10+, 120Hz\r\nMàn hình phụ: 6.23\"\" 2268x832, HD+ Dynamic AMOLED 2X (24.5:9) Infinity-O Display, 38ppi, 120Hz\r\nTrọng lượng\r\n\r\n271g\"', 0, 0.0),
(82, 'Samsung Galaxy S23 Ultra ', 26990000.00, 100, 's23u-1.png,s23u-2.png,s23u-3.png,s23u-4.png,thumb-anhchinh13.png', 0.00, 0, 1, '2023-03-17 13:26:50', '2023-03-17 13:59:48', 'Samsung Galaxy S23 Ultra là điện thoại cao cấp của hãng điện thoại Samsung được ra mắt vào đầu năm 2023. Điện thoại Samsung S23 series mới này sở hữu camera độ phân giải 200MP ấn tượng cùng một khung viền vuông vức sang trọng. Cấu hình máy cũng là một điểm nổi bật với con chip Snapdragon 8 Gen 2 mạnh mẽ, bộ nhớ RAM 8GB mang lại hiệu suất xử lý vượt trội.', 3, 10, '\"Kích thước màn hình\r\n\r\n6.8 inches\r\nCông nghệ màn hình\r\n\r\nDynamic AMOLED 2X\r\nCamera sau\r\n\r\nSiêu rộng: 12MP F2.2 (Dual Pixel AF)\r\nChính: 200MP F1.7 OIS ±3° (Super Quad Pixel AF)\r\nTele 1: 10MP F4.9 (10X, Dual Pixel AF) OIS,\r\nTele 2: 10MP F2.4 (3X, Dual Pixel AF) OIS Thu phóng chuẩn không gian 100X\r\nCamera trước\r\n\r\n12MP F2.2 (Dual Pixel AF)\r\nChipset\r\n\r\nSnapdragon 8 Gen 2 (4 nm)\r\nDung lượng RAM\r\n\r\n8 GB\r\nBộ nhớ trong\r\n\r\n256 GB\r\nPin\r\n\r\n5.000mAh\r\nThẻ SIM\r\n\r\n2 Nano-SIM + eSIM\r\nHệ điều hành\r\n\r\nAndroid\r\nĐộ phân giải màn hình\r\n\r\n1440 x 3088 pixels (QHD+)\r\nTính năng màn hình\r\n\r\n120Hz, HDR10+, 1750 nits, Gorilla Glass Victus 2\r\nTương thích\r\n\r\nBút S-Pen\"', 0, 0.0);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `tbl_sanpham`
--
ALTER TABLE `tbl_sanpham`
  ADD PRIMARY KEY (`masanpham`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `tbl_sanpham`
--
ALTER TABLE `tbl_sanpham`
  MODIFY `masanpham` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=83;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
